### ISSUE TITLE
Add Current situation  to the documentation

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#1]
Description:
Add Current Situation to the documentation

"Try to use this section to prepare for the next section of needs. For example in a project concerned with used car owner/repair history you could emphasize the point that there is a large used car market and that for used cars information about the car's history is more important than for new cars. If you have to make reference to data like percentages or estimates, its good if you include where you found it or a source."

**Comment by PinkSylvie** [comment]
Hello! I see this part of the documentation is missing, would just like to remind you that tasks are due tomorrow so that we have Friday for review and so that we are able to turn the documentation in.

**Comment by FrancesC8** [comment]
@irsaris @PinkSylvie I completed the task and added the contents to the documentation.

**Comment by PinkSylvie** [comment]
> @irsaris @PinkSylvie I completed the task and added the contents to the documentation. 

Just checked! 👍
