### ISSUE TITLE
Implement pet stages

### ISSUE THREAD

**Issue by JonathanDebug** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#101]
The pet will have 3 stages of growth. Baby, Young and Adult Stages. The pet will change designs every stage of growth. You'll divide the time from the date of birth till the day of the exam, and the pet will change stages every 1/3 of the time. For Ex. If there's three days till the exam the pet will be on its baby stage for 1 day, on its young stage for 1 day and on its adult stage for 1 day.

**Comment by irsaris** [comment]
There’s 3 growth stages. In every third of the time from the pet’s birth till the exam date the pet will change its design. For example if there’s three days before the exam and three growth stages. The pet will be in its baby stage for a day, its kid stage for a day and its adult stage for a day

**Comment by JonathanDebug** [comment]
The task has been completed, here is the PR link: https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/pull/210
