### ISSUE TITLE
[Lecture Topic Task] Snapshot testing on Pet Shop

### ISSUE THREAD

**Issue by JonathanDebug** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#102]
Implement snapshot testing into Pet Shop component

"Snapshot testing is a type of output comparison testing. This type of testing ensures that your application adheres to the quality characteristics and code values of your development team. Snapshot tests are useful when you want to make sure your UI does not change unexpectedly." [Source](https://circleci.com/blog/snapshot-testing-with-jest/#:~:text=Snapshot%20testing%20is%20a%20type,UI%20does%20not%20change%20unexpectedly.)

**Comment by Negroni1** [comment]
Hi @JonathanDebug do u plan to do the background designs as well?
