### ISSUE TITLE
Implement pet variety

### ISSUE THREAD

**Issue by JonathanDebug** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#104]
Implement a system for the design of the pet and its growth stages to change.

**Comment by Elielh17** [comment]
Pet Variety implemented. When creating an new pet, the option to choose a pet type is provided. The images of the pet change depending on the type that the user chooses. Right now, all the images of Dog and Cat pets are placeholders or dummy images to be replaced in the future. Here is the commit: https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/commit/25f2fdcf0272e708a08c6dd23bbbfb6afb1b17ff

![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/70725243/56f1661d-f04e-4c0f-939c-5e94b1749ae7)

![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/70725243/d3c38d15-890a-4898-9351-f87dd9ecf968)

![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/70725243/ca161301-6c55-4d64-a104-93fe4c7c9911)
