### ISSUE TITLE
Display Animated Pets on Pet Creation Screen

### ISSUE THREAD

**Issue by Mark-Anton** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#105]
Display a selecte pet on pet creation screen with its respctive animations

Difficulty: 3
Priority: 5

**Comment by Mark-Anton** [comment]
Implemented Players stats and temporary values to be linked with other branches, inputs and overall score verification and validation of the user.

![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/42784582/f0b35e9d-76b2-46d0-afba-fec72fb3f3e3)

PlayerStats [#223](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/pull/223)

**Comment by irsaris** [comment]
hello i saw the screenshots, does that mean that this task was already completed?

**Comment by Mark-Anton** [comment]
![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/42784582/036d272b-2f6f-4ef6-bd19-6cd858119d76)
frog animation is set. all other pets do not have animations

**Comment by PinkSylvie** [comment]
PR?

**Comment by Mark-Anton** [comment]
https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/pull/343
