### ISSUE TITLE
Set up dummy loading screens

### ISSUE THREAD

**Issue by JonathanDebug** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#107]
Design and setup the loading screens for the app.

**Comment by JonathanDebug** [comment]
https://www.figma.com/file/waYXP2pqU7MOiLq5VuCxMQ/Loading-Screen-Design?type=design&t=xDroisOViGaCBhO5-6 @irsaris  @PinkSylvie  here is the design of the loading screens, there's 2 drafts currently but draft 2 is preferred.

**Comment by irsaris** [comment]
Nice work!

**Comment by JonathanDebug** [comment]
Petition to convert the loading screen design task into an LTT to leverage its potential for performance and error handling assessment. The loading screen serves as a crucial checkpoint for evaluating our app's performance and error response mechanisms. By conducting comprehensive tests, we can optimize loading times, ensure effective error handling, and enhance the overall user experience. This task is similar to https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/issues/2.  @irsaris @PinkSylvie

**Comment by irsaris** [comment]
Thoughts on this @PinkSylvie ?

**Comment by JonathanDebug** [comment]
I understand your concern about its current implementation status. However, I'd like to clarify that my proposal was made within the context of Milestone 1, where fewer project advancements were expected. In Milestone 1, the UI sketching task was recognized as an LTT despite its implementation. Similarly, the loading screen design task was proposed with the intention of leveraging its potential for performance and error handling assessment, aligning with the initial project expectations. Given the unforeseeable nature of project developments, I couldn't predict the loading screen's implementation status accurately. It was communicated that the loading screen would be part of the project scope initially. Considering these factors, I respectfully request reconsideration of my petition, as it aligns with Milestone 1 expectations and project scope at the time of task assignment.

**Comment by PinkSylvie** [comment]
#2 was recognized as an LTT task because even in the infancy of the project, not only designs tasks were done, but implementation, and as such testing. Many of the screens in the UI have running tests, like the Flashcards, Minigame screens and pet creation. The same cannot be said about loading screens

**Comment by PinkSylvie** [comment]
The loadings screens were a possibility but unless you kept track of them through all milestones, only you could guarantee their implementation if you picked up the task

**Comment by JonathanDebug** [comment]
While it's accurate that the UI has undergone implementation and testing phases, it's important to note that the task initially involved solely the sketching process, not the subsequent implementation and testing phases. However, I want to underscore that my proposal during Milestone 1 regarding the loading screen design task as an LTT stemmed from its potential significance in assessing performance and error handling capabilities, irrespective of its current implementation status. Additionally, during the project's initial planning stages, it was indicated that the loading screen implementation would be addressed by another developer since I am working with the Pet team. This allocation of tasks meant that, at that time, my involvement with loading screen implementation was not anticipated, as my focus was dedicated to tasks related to the pet aspect of the project.

**Comment by PinkSylvie** [comment]
stemmed from its potential significance in assessing performance and error handling capabilities. But what significance is there if it has nothing to show on that significance

**Comment by JonathanDebug** [comment]
I understand your perspective. In Milestone 1, the focus was on laying the foundation for future tasks, and the significance of each task was evaluated based on its potential contribution to the project's objectives. While the implementation of the loading screen would have been ideal, the uncertainty of project progression at that stage meant that guarantees for later tasks were not assured. Given this context, marking the loading screen design task as a Lecture Topic Task (LTT) in Milestone 1 seems reasonable, as it aligns with the proactive approach to addressing potential challenges early in the project. Just as other tasks were recognized as LTTs despite lacking full implementation, the emphasis should be on the conceptual groundwork laid for future testing strategies rather than solely on immediate outcomes. When it comes to this task, im talking in the perspective of milestone 1.

**Comment by PinkSylvie** [comment]
In the perspective of milestone one several of the UI screens had guaranteed implementation, and were implemented in milestones 1, because without those screens the app wouldn't exist like the pet screen, flashcards, and Minigames. And BDD and TDD testing were done on that Milestone as well

**Comment by PinkSylvie** [comment]
It's hard to justify the importance of something that wasn't implemented.

**Comment by PinkSylvie** [comment]
After further reconsideration this task can be an LTT but you have to include your defense for the task being an LTT in the task description

**Comment by JonathanDebug** [comment]
Thank you for your reconsideration, will be updating it shortly.
