### ISSUE TITLE
[Lecture Topic Task] Test Plan

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#108]
Develop a test plan for the mobile app, focusing on features like virtual pet care and flashcard quizzes. This plan will outline testing methodologies, cases, and schedules to ensure the app's functionality across devices. The aim is to detect and resolve issues, guaranteeing a smooth user experience.

**Comment by PinkSylvie** [comment]
Could you add a link to the test plan on a comment so that the completion of the task is proved and documented here in GitHub?

**Comment by irsaris** [comment]
Yeah, it's on the Drive. Here's the document https://docs.google.com/document/d/1tGMUS1hLaGCy076OgQiSizjGuRgUtlEvAM0rA_cp-Xs/edit?usp=drive_link
