### ISSUE TITLE
Brainstorm and Sketch Minigame Ideas

### ISSUE THREAD

**Issue by Adhel-Esteban1** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#12]
Initiate a creative brainstorming session to generate diverse and engaging minigame concepts for the StudyPet mobile app. Encourage team collaboration and consider the educational objectives of the app. Once ideas are generated, sketch rough outlines or storyboards for each minigame to visualize the gameplay and mechanics. Ensure that the minigames align with the app's theme and enhance the learning experience. Document the key features and objectives of each minigame to guide the development process. This task sets the foundation for creating interactive and educational studying experiences within the StudyPet app.

**Comment by Adhel-J** [comment]
Added a document with 8 ideas for minigames or possible mechanics of the app

**Comment by irsaris** [comment]
@Adhel-J can you link the document here?

**Comment by Adhel-J** [comment]
Link to the Doc: https://docs.google.com/document/d/1AP0irNdqh5m-whqNYc1kx6QhKArnRT48/edit?usp=drive_link&ouid=110275428539001887658&rtpof=true&sd=true
