### ISSUE TITLE
[Doc Feedback] Fix Terminology in Documentation 

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#123]
"
- [x] I would recommend not to define a student as "Individuals who utilize the Study Pet application to manage their study materials, interact with their virtual pets, and engage in learning activities." Why? Think about it: taken strictly it means that as long as there's not yet a Study Pet app, there are no students, since no one can be using this app yet. Also check your other definitions, for example, study methods...

- [x] That terminology is very entity-oriented (I do not see any events, actions, or behaviors). Most prominently missing is the definition of the term "to study".

"

**Comment by PinkSylvie** [comment]
We are missing  your part in the documentation

**Comment by JorgeC08** [comment]
Both task are completed.

**Comment by PinkSylvie** [comment]
Please take this into account and fix the rest of the definitions: "taken strictly it means that as long as there's not yet a Study Pet app, there are no students, since no one can be using this app yet". Definitions refering to the study pet arent true because the app doesnt exist yet

**Comment by JorgeC08** [comment]
> Please take this into account and fix the rest of the definitions: "taken strictly it means that as long as there's not yet a Study Pet app, there are no students, since no one can be using this app yet". Definitions refering to the study pet arent true because the app doesnt exist yet

Updated both definition to not make it dependent of the Study Pet app since it doesn't exist yet.

Please verify.
