### ISSUE TITLE
[Doc Feedback] Fix Domain, Actions, and Behaviors and Function Signatures in Documentation 

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#125]
"
- [ ] Your events, actions, and behaviors are all application-oriented. What are corresponding domain events, domain actions, and domain behaviors?

- [ ] Function signatures do not belong in a section by themselves. Their purpose is to help a reader understand the actions/operations better, so they belong together with those actions/operations. As presented these function signatures are not really of much help. For example, "ListUserCourses": what is a "UserCourse" and why does it need to be supplied to the function when we already have the "User", isn't that same information available through navigation from the "User" parameter? Or the function "CourseCreation" takes only a "UserCourse" and a "Course" and returns a "UserCourse", but what if I, at a later time, have a "User" and want to get that "User"'s list of courses? Moreover, most/all of the functions do not represent domain activities/actions/operations.

"

**Comment by PinkSylvie** [comment]
Your task is due in half an hour
