### ISSUE TITLE
[Doc Feedback] Fix Machine Requirements in Documentation 

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#127]
"Machine requirement need more detail: if you say that a requirement is to operate seamlessly on iOS and android devices, then someone might interpret this very broadly as meaning ALL versions of the two operating systems going back to a time when dinosaurs were still roaming the earth..."

**Comment by Axl4767** [comment]
@PinkSylvie @irsaris I changed the machine requirements based on the feedback.
