### ISSUE TITLE
[Doc Feedback] Fix Current Situation in Documentation 

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#129]
"In the current situation (and therefore also in the needs, since they arise from the current situation) your system does not exist and therefore it's much more helpful to think about the people in terms of their roles or functions that they have. "User" is a term that makes no sense here. Who is it that needs assistance? We could call such a person a "learner", "student", "skill seeker",... all these emphasize the role and deemphasize the reliance on implementing a system. That's what we need here: the needs independently of the means to achieve the needs. In the "ideas" section you are then right to talk about the means that you choose to satisfy the needs."

**Comment by PinkSylvie** [comment]
@Fabian-J you already have the needed score that’s why I took it from you

**Comment by Fabian-J** [comment]
I wasn't sure how many points I had. That's fair enough

**Comment by Adhel-J** [comment]
Documentation section has been modified to fix the errors that the professor pointed out.

**Comment by PinkSylvie** [comment]
What did you add_ New things must be highlighted green, things changed are not only strikes through and highlighted red. Everything looks the same,now its just double except one of them is strike through

**Comment by PinkSylvie** [comment]
@irsaris could you give an eye to it as well?

**Comment by Adhel-J** [comment]
added highlighting

**Comment by PinkSylvie** [comment]
please highlight what you changed not everything that is within what you changed. The way you did it is hard to tell what's different

**Comment by irsaris** [comment]
@Adhel-J did you copy paste the new addition and highlighted one green and the other red?
they both have the same contents, that's not possible. You must edit what was written originally by leaving unedited words alone, removing words by striking them and highlighting them red and add new words by highlighting in green. You can look through the rest of the doc to see how these changes are made. Fix it.

**Comment by PinkSylvie** [comment]
The professor mentioned that current and needs have to be reflected outside our system, those exist beside our app. So please don't mention the app on the current situation or needs. The app is a solution to the need's that why it is mentioned

**Comment by Adhel-J** [comment]
can the app be mentioned in the ideas?

**Comment by Adhel-J** [comment]
anyway changed the mention of "users who use the app" with equivalent words such as "learner" or "student" can you check again?
