### ISSUE TITLE
[Doc Feedback] Fix Interface Requirements in the Documentation

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#130]
"To distinguish between domain requirements, interface requirements, and machine requirements we want to state the domain requirements in such a way that they only reflect what can be derived from the domain. When you say "create a virtual pet" that's a relatively coarse statement: he creating could involve interface aspects (how is the creation kicked off?) What data does the user have to provide that goes into the creation? Etc. etc. These would be interface requirements."

(basically 'creating a virtual pet' should be moved to interface requirements instead and you should specify more that goes into 'creating a virtual pet', is what i think)

**Comment by AnthonyMed13** [comment]
@PinkSylvie @irsaris  if you could check this in order to close the issue, added the changes for the interface requirements to the documentation
