### ISSUE TITLE
[Doc Feedback] Fix Concept Analysis in Documentation

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#131]
"Concept formation is pretty well done, but try to take a less implementation-oriented perspective."

**Comment by PinkSylvie** [comment]
We are missing  your part in the documentation

**Comment by JorgeC08** [comment]
I think that I've completed the task. Left **Incentive or Motivation** as is. I think that it looked good.

**Comment by irsaris** [comment]
did you update the change log?

**Comment by JorgeC08** [comment]
I forgot that part. I’ll updated it now
________________________________
