### ISSUE TITLE
[Lecture Topic Task] Implement in project from The Fuzzing Book 

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#132]
This was material the professor assigned the days there were not any class. If it's coding make sure to put it in the project code as well as document it in the Milestone doc. If it's just documentation, make sure it is well done in the Milestone doc.

"https://www.fuzzingbook.org/html/00_Table_of_Contents.html
your task is to proceed to the chapter on "Testing Graphical User Interfaces". This means to will have to work through the chapters leading up the this chapter. Then apply the tools of these chapters to your project."

**Comment by irsaris** [comment]
Remember to document it in the Milestone doc.

**Comment by diego-velez-upr** [comment]
> Remember to document it in the Milestone doc.

Which doc is that?

**Comment by Adhel-Esteban1** [comment]
@diego-velez-upr I believe it's this one:

https://docs.google.com/document/u/1/d/1EubiyUR71VXWMOAWElBCpmxKs2GHZP9lTDB4XiD8c2g/mobilebasic

**Comment by irsaris** [comment]
> > Remember to document it in the Milestone doc.
> 
> Which doc is that?

Its the Milestone 2 document that can be found in the shared Drive of this project.

**Comment by diego-velez-upr** [comment]
> @diego-velez-upr I believe it's this one:
> 
> https://docs.google.com/document/u/1/d/1EubiyUR71VXWMOAWElBCpmxKs2GHZP9lTDB4XiD8c2g/mobilebasic

Oh the documentation? Already added under 4.1 TDD testing (fourth case)

**Comment by irsaris** [comment]
Make sure new additions are in green highlight. Also, I was looking at the change log and the changes weren't documented make sure to do that.

**Comment by diego-velez-upr** [comment]
> Make sure new additions are in green highlight. Also, I was looking at the change log and the changes weren't documented make sure to do that.

Changes documented
