### ISSUE TITLE
Design Pet Backgrounds

### ISSUE THREAD

**Issue by Negroni1** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#138]
Design multiple pet backgrounds, such as bedroom, patio, kitchen, and lounge.

**Comment by Negroni1** [comment]
Backgrounds Design:


![Image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/64982360/c71876da-93b0-4937-a0aa-f346f230d9ac)
![Image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/64982360/9adaf541-c583-4448-8954-241538e3f7fa)
![Image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/64982360/b551cb9e-d1d1-4f6c-a43c-4c99eed4f330)

**Comment by PinkSylvie** [comment]
I think they look adorable, it'd be nice if the palette was closer to the app's colors tho. Other than that I think it looks great!
