### ISSUE TITLE
Design New Pets!

### ISSUE THREAD

**Issue by Negroni1** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#139]
Design new pets such as cats, pigs, rats, and others (open for suggestions)

**Comment by Negroni1** [comment]
Hi @PinkSylvie This are some of designs of the new pets that I have come up with (bear, pig, otter, penguin, cat) . If you have an idea of other designs lmk

![Image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/64982360/efbaff83-07fa-4ec1-8617-22287fad4e57)

**Comment by PinkSylvie** [comment]
@Negroni1 How about a yellow bunny?

**Comment by Negroni1** [comment]
@PinkSylvie 


![Image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/64982360/8a3bc3aa-c316-4233-aedc-cdc3af805b53)

**Comment by PinkSylvie** [comment]
I think it looks great! Could you do a dog as well? For UPR sake based on Tarzan? I'm gonna close the task tho since it was done with the first set! The designs look so cure.
