### ISSUE TITLE
Add Team and Partners to Documentation 

### ISSUE THREAD

**Issue by benjaminCMD** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#14]
- Add the fullnames of every team members into the documentation. 
- You can these finds within the moodle page or the Github username document
- Partners work closely related to the team, but are not directly apart of it. They have a higher stake in the project, so customers and users are not normally partners. 
- With partners, the only partner, who is not a team member, but work closely related to us is the professor. You can add his name below partners

**Comment by PinkSylvie** [comment]
Just checked, nice work!
