### ISSUE TITLE
[Lecture Topic Task] TDD: Continue to perform and document unit tests on new StudyPet components, implementations and features.

### ISSUE THREAD

**Issue by DiegoLIRodriguez** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#144]
Previous tests were performed on developing environment and flashcard components. As new features are implemented, unit tests must be carried out in order to ensure functionality and quality. These tests are documented thoroughly, step-by-step, with explanations added for every iteration, albeit success or failure; for the betterment of the team and the project as a whole.

Suggested Difficulty: 7
Suggested Urgency: 6

*As feature development progresses, further understanding of code and the domain is necessary, so I recommend a difficulty raise for assignees sake (+3 from previous milestone).

**Comment by PinkSylvie** [comment]
There are several tasks already where they focus on TDD tetsing of new features. Pick a focus

**Comment by DiegoLIRodriguez** [comment]
Okay, decided to adjust focus on the Flashcard components per se. Testing will be done on upcoming developments and features. Suggested difficulty: 4
Suggested priority: 6
