### ISSUE TITLE
Implement setting to change backgrounds

### ISSUE THREAD

**Issue by gabrielpadilla7** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#146]
In issue #138, it is stated that multiple background will be available to the user. Here, the implementation to be able to switch out the backgrounds will be done. Ideally, this will be put in settings.

**Comment by diego-velez-upr** [comment]
I think I could work on this issue.

**Comment by Adhel-J** [comment]
@diego-velez-upr do you want to take this task? I prefer to work on the documentation.

**Comment by diego-velez-upr** [comment]
> @diego-velez-upr do you want to take this task? I prefer to work on the documentation.

Sorry, I didn't know you already had this task. If you don't want it, though, I'll take it.

**Comment by Adhel-J** [comment]
take it
