### ISSUE TITLE
Implement New Pet Creation and Selection [Multiple Pets]

### ISSUE THREAD

**Issue by Mark-Anton** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#148]
Following up on issue #84. Create a pet file that contains new/current pets and a short description of their status their status. When a user select a pet they wish to view it will take the user to the status window for that specific pet. Make sure the data of the multiple pets is stored somewhere.

Difficulty: 3
Priority: 5

**Comment by irsaris** [comment]
Hello, where is the PR for this?

**Comment by Mark-Anton** [comment]
My Pets Selection Screen [#224](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/pull/224)
