### ISSUE TITLE
[Lecture Topic Task] Add Needs to Documentation

### ISSUE THREAD

**Issue by benjaminCMD** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#15]
Add Needs to Documentation
 - Create a list of needs related to the domain, not the system-to-be. 
- When listing down make sure that needs you present are not ideas you have solving them
- Example: a project improving the situation with people having too many calendars "the tool should direct all the tasks and events into one single place" is not a need. 
- Instead, there is a need for people to be able to find all their calendar events in one place.

**Comment by irsaris** [comment]
@benjaminCMD you need to redo this section. Why is it only talking about exam dates?

**Comment by benjaminCMD** [comment]
I redid the section. Please check if it is alright or if there is anythig I need to change

**Comment by PinkSylvie** [comment]
Just checked, nice work!
