### ISSUE TITLE
 UI and UX for Pet Creation 

### ISSUE THREAD

**Issue by Mark-Anton** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#150]
Follow up on issue #84.  Implement a revised user inferface for the pet creation window to make it more attractive to the user and better the users experience.

Difficulty: 4
Priority: 4

**Comment by FrancesC8** [comment]
Please, consider adding the pet's sleep schedule in the pet creation view. This would need **at least** Sleep time (that is, actually going to sleep) and wake up time.

**Comment by irsaris** [comment]
Hello, where is the PR for this?

**Comment by irsaris** [comment]
any update on this?

**Comment by irsaris** [comment]
Task will be moved for next milestone

**Comment by FrancesC8** [comment]
> Hello, where is the PR for this?

Este task lo tiene asignado @Mark-Anton.

**Comment by irsaris** [comment]
> > Hello, where is the PR for this?
> 
> Este task lo tiene asignado @Mark-Anton.

Yeah, it's been moved for next Milestone

**Comment by Mark-Anton** [comment]
https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/tree/UI-and-UX-for-Pet-Creation-%23150

Stylized the ui/ux and background of the page

**Comment by irsaris** [comment]
You linked the branch, has the PR already been merged?

**Comment by Mark-Anton** [comment]
https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/pull/339
