### ISSUE TITLE
Fix Pet Creation Issue

### ISSUE THREAD

**Issue by Mark-Anton** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#152]
Follow up on issue #84. Currently the Pet Creation page does not create a new pet or record the pets status in the status window.

Key objectives:

-When creating a new pet, it creates a new file in the status window and have its status change in realtime.
-Once the pet is created, creates a new flash card file for that specific pet and presets exam dates that can be adjusted by the user.

Difficulty: 3
Priority: 4

**Comment by irsaris** [comment]
this wasnt added to any board or anything, will you still be doing this?

**Comment by Mark-Anton** [comment]
This issue is still pending. I have transfered the responsibility of this task's completion to Sebastian A Torrez-Segarra (github user: PurpleDerg) as i will be completing Implement "My Pets" Screen #93. This was a task made as a continuation of the pet creation screen, as it was not fully develped properly.

**Comment by irsaris** [comment]
Ok, can @PurpleDerg suggest scoring?

**Comment by PurpleDerg** [comment]
I believe the scoring that it has right now is appropiate

**Comment by PurpleDerg** [comment]
I would like to clarify that my name is Sebastian Granda as well.

**Comment by irsaris** [comment]
was this fixed? i dont see a PR

**Comment by PurpleDerg** [comment]
working on this at the moment, could have it done for Monday

**Comment by PurpleDerg** [comment]
This was JUST fixed

**Comment by PurpleDerg** [comment]
made a PR
