### ISSUE TITLE
Write down Ideas Into the Documentation

### ISSUE THREAD

**Issue by benjaminCMD** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#16]
- Write down a list of ideas into the documentation that solves the needs that were listed beforehand. 
- These ideas can include system-to-be features 
- Present the ideas in a clear and concise manner of one-two sentences

**Comment by PinkSylvie** [comment]
Hello! I see this part of the documentation is missing, would just like to remind you that tasks are due tomorrow so that we have Friday for review and so that we are able to turn the documentation in.

**Comment by benjaminCMD** [comment]
Finished with this task. If there is anything I need to add, then please let me know

**Comment by PinkSylvie** [comment]
Just checked, nice work!
