### ISSUE TITLE
Video for Milestone 2

### ISSUE THREAD

**Issue by Adhel-J** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#160]
Create a new video for milestone 2 of the project incorporating the new presentation and a better demo interface

After Milestone 1 Notes:

The professor commented about the video length last milestone so for this one it'd be preferable for the length of the video to be 8 - 15 mins. Topics of discussion could be the test plan for the milestone which will be provided to you by the person working on it (TAsk #134). The results of the test plan and what we'll be working on for the next milestone

**Comment by gabrielpadilla7** [comment]
The demo issue has been put up, I will do the demo

**Comment by irsaris** [comment]
#186 would be the voiceover of the video, if youre interested doing that task as well. Video would just be putting everything together I believe.

**Comment by irsaris** [comment]
Will be closed with the promise of it being completed before the deadline next week.
