### ISSUE TITLE
Design/Implement `Eat` Page

### ISSUE THREAD

**Issue by CaribbeanCool** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#161]
# Description
This task involves designing and creating the `Eat` page where the user can play a minigame with flashcards to feed their pet when necessary.
# Points
Tentative [ Difficulty(4) x Priority(4) ]

**Comment by CaribbeanCool** [comment]
Here is the link for the Figma design [Link to Figma](https://www.figma.com/file/06srqyYzX4tgifBA9j1w3X/Study-Pet-Designs?type=design&node-id=0-1&mode=design&t=IDps9DagIA2MJdvy-0)

# Image 1:
![Overview of Eating Page](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/92653848/991e5b26-fd01-4afe-be3f-5ef7efae9c29)
# Image 2:
![Result of Eating minigame](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/92653848/1ab3e69c-a5b9-4e7e-985c-d37a7d0e79f7)

**Comment by irsaris** [comment]
Looks good! Let me know when you're done with the other part of the task as well.
