### ISSUE TITLE
[Lecture Topic Task] Add tests for Pet Sleep Schedule feature

### ISSUE THREAD

**Issue by FrancesC8** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#166]
Create a test suite that contains all the necessary test cases for Pet Sleep Schedule feature. Use the help of test frameworks that are compatible with the existing system, including (unit tests, test runner, mocking libraries and/or test formats).

Consider implementing the feature using TDD.

Suggested points -> Priority(Intermediate) * Difficulty(Intermediate) = 4 * 4 = 16

**Comment by FrancesC8** [comment]
@Negroni1 @irsaris @PinkSylvie Se me habia olvidado comentar en mis issues que estan completados, podran ver la implementacion en el PR atado. Pude implemetar alrededor de 24 tests a funciones comunes de Pet Sleep Schedule feature. Podran ver mas detalles sobre code coverage en el PR.

**Comment by irsaris** [comment]
Estos tests van a estar documentados en el doc?

**Comment by FrancesC8** [comment]
> Estos tests van a estar documentados en el doc? @FrancesC8

Si, ya los añadi a la documentacion.

**Comment by irsaris** [comment]
ok thanks
