### ISSUE TITLE
Design Pet Goodbye

### ISSUE THREAD

**Issue by Negroni1** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#167]
Design Pet goodbye (Goodbye happens the day after the exam), this could include animations, notifications, and others.

**Comment by Negroni1** [comment]
Hi! @PinkSylvie here is the design for the pet goodbye feature, lmk what u think: https://www.figma.com/file/tWQJb1GAeiwX0Vr66OJe24/Pet-Goodbye?type=design&node-id=0%3A1&mode=design&t=dbTkQSArBjjJRq10-1

**Comment by Negroni1** [comment]
Ok! Thank you! I'll make does changes in the implementation phase of the goodbye feature (#168 ). Also, I was thinking of adding some extra stuff (q no son necesarios para el cumplimiento of the task) -> ideas: writing animation (basicamente q las letras vayan apareciendo) y maybe añadir voice lines del pet (como animal crossing). Let me know what you think and if possible mark this issue as completed.

**Comment by PinkSylvie** [comment]
@Negroni1 I like the idea a lot! But you could make it those extra things as a task for next milestone so you could get scored appropriately. Unless you want to do those extra things for this one as well
