### ISSUE TITLE
Implement and connect `happiness` aspect to the Pet

### ISSUE THREAD

**Issue by CaribbeanCool** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#169]
# Description
When feeding and cleaning the Pet, it gains happiness, which is an aspect of its survivability, and we have to connect this aspect to the Pet itself.
# Points
Tentative(Difficulty 3 x Priority 4)

**Comment by irsaris** [comment]
Hello, please suggest urgency and difficulty scores.

**Comment by CaribbeanCool** [comment]
@irsaris done
