### ISSUE TITLE
Add Scope and Span into the Documentation 

### ISSUE THREAD

**Issue by benjaminCMD** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#17]
Scope: 
- It should go all go over all aspects of your project in a broad perspective such as requirements, needs, and implementations, etc.
- When discussing about the score audience, must be done in a broad terms. For example, "students" would be a good term for scope, while "UPRM students" is not since it is being specific and more suited towards the span. 

Span: 
- This section is a more detailed scope. You can specify how score audience mainly towards UPRM students
- Elaborate on project details such as front-end languages, back-end languages, potential databases, software used when designing the pets
- You can specify deliverables such as the tool deplyed as mobile use, mock-ups and wireframes for the project, or weekly progress reports

**Comment by PinkSylvie** [comment]
Hello! I see this part of the documentation is missing, would just like to remind you that tasks are due tomorrow so that we have Friday for review and so that we are able to turn the documentation in.

**Comment by PinkSylvie** [comment]
Just checked, nice work!
