### ISSUE TITLE
[Lecture Topic Task] Add several scenarios of the team's actual use of prodding debugging into the documentation

### ISSUE THREAD

**Issue by bally7301** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#172]
Follow alongside developers record and add onto teh docunentation how they debugged the implementations of essential components of teh project application. Document their uses of debugging and show several scenarios in which they use debugging. Their scenarios must make use of breakpoints (and at
least one other feature of the debugger) in a useful way. The
purpose of the debugging can be finding a defect, but it can also be
exploring whether a function or statement actually works as
expected. State clearly what you are looking for, what is the
hypothesis, doubt, question,… Any debugger can be used as long as
the team meets the above requirements.

Preferably via screenshots and some explanation on what was being debugged

**Comment by bally7301** [comment]
mediam difficulty and medium priority

**Comment by irsaris** [comment]
Hello, this is missing in the document.

**Comment by Fabian-J** [comment]
It's not. Task #159 meets most of the criteria for this outside of the extra debugger feature. I don't believe there would be enough difference for an entirely new section in the documentation when simply adding the extra debugger feature is enough.

**Comment by irsaris** [comment]
Ok ill close this then
