### ISSUE TITLE
[Lecture Topic Task] Run Load Tests and add them to the Documenation according to the milestone criteria

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#176]
Through specialized testing software, load testing places a simulated “load” or demand on your web application to ensure it remains stable during operation.

For this task follow up on taks #175, and run several load test scenarios. In the documentation dicuss for each one:
    • Plausible load expectations
    • Typical usage scenarios and how you used them for load
      testing
    • Discuss and explain your load testing setup and how it
      relates to their expected load.
    • Interpret the results observed for each scenario

Do all of these for at least two scenarios

**Comment by PinkSylvie** [comment]
We are missing  your part in the documentation

**Comment by bally7301** [comment]
Esta parcialmente me fallacy unos detalles pero se encuetra en la apartment 4

**Comment by irsaris** [comment]
> Esta parcialmente me fallacy unos detalles pero se encuetra en la apartment 4

Not sure que se entiende que dijiste aqui, puedes aclarar?

**Comment by bally7301** [comment]
Ese me out corrigió por el te lado era “Esta parcialmente echo faltan unos detalles pero se encuetra en la parte 4”

**Comment by bally7301** [comment]
Teclados

**Comment by irsaris** [comment]
Okay make sure to add those details and also updated the changelog table

**Comment by bally7301** [comment]
ya termine el escrito que era solo añadir una linea para el Plausible load expectations. porfavor revisen y digan si falta algo.
