### ISSUE TITLE
[Lecture Topic Task] Make sure the project utilizes Hoare Logic and document how does it do it in the documentation

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#178]
[Hoare logic](https://en.wikipedia.org/wiki/Hoare_logic) is a formal system with a set of logical rules for reasoning rigorously about the correctness of computer programs.
Examples of Hoare logic are: pyrefine, https://www.key-project.org/, frama-c

Make sure the project utilizes Hoare Logic and document how does it do it with at least one meaningful example in the documentation.
A recommendation the professor gives for this tasks is that if you want to use tool support, but cannot find a tool for the project's language, you can rewrite that function in a different language for which there's a tool available.

**Comment by irsaris** [comment]
Hello, please suggest urgency and difficulty scores.

**Comment by Fabian-J** [comment]
An example of Hoare Logic has been provided. I couldn't get any tools working so I opted to do a manual analysis.
