### ISSUE TITLE
[Lecture Topic Task] Make sure the project uses types and document how and where does it in the documentation

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#179]
[Further explanation on types in class slides] 
Make sure the project utlizes types in at least one non-trivial example function and document the example of their use in the dosumentation. These types would be used to comunicate insights about the functions and enhance understandability.
Ex. By introducing meaningful types to
      represent domain concepts such as Student, Course, or Doctor,
      Appointment, etc.

**Comment by benjaminCMD** [comment]
@PinkSylvie @irsaris I just finished making a draft for the Types section within the document. If you any tips or suggestions for the changes I make, then @ me
