### ISSUE TITLE
Research Spaced Repetition algorithm

### ISSUE THREAD

**Issue by diego-velez-upr** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#18]
The goal of this task will be to research how to implement a [Spaced Repetition algorithm](https://en.wikipedia.org/wiki/Spaced_repetition) for the flashcards as a way to increase the rate of learning of the user.

**Comment by irsaris** [comment]
@PinkSylvie is this still worth doing?

**Comment by PinkSylvie** [comment]
Research could be worth doing. But unless all task in the idea pile are taken up and everyone already has the lecture topic tasks they need I'm unsure if it'd be worth implementing

**Comment by irsaris** [comment]
do you have anything to show for this?
