### ISSUE TITLE
[Lecture Topic Task] Set a Mutation Testing tool on Jest for the project

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#180]
Mutation testing is designed to ensure the quality of a software testing tool, not the applications it analyzes. Mutation testing is typically used to conduct unit tests. The goal is to ensure a software test can detect code that isn't properly tested or hidden defects that other testing methods don't catch.

For this task set up a mutation testing environment in the project using Jest and make sure tests can be run in them.

[Jest Setup](https://jestjs.io/docs/tutorial-react-native)

To complete this task, tests must be able to be run and you must show an example of a dummy test running on it

**Comment by FrancesC8** [comment]
Suggested points -> Priority(Urgent) * Difficulty(Easy) = 8 * 2 = 16

**Comment by FrancesC8** [comment]
@Negroni1 @irsaris @PinkSylvie Se me habia olvidado comentar en mis issues que estan completados, podran ver la implementacion en el PR atado. Adicionalmente, añadí una seccion en la [documentacion](https://docs.google.com/document/d/1EubiyUR71VXWMOAWElBCpmxKs2GHZP9lTDB4XiD8c2g/edit?usp=sharing) sobre mutation testing (seccion 4.8) y podran ver mi entrada en el changelog.
