### ISSUE TITLE
[Lecture Topic Task] Run Mutation Tests and discuss the results obtained in the documentation

### ISSUE THREAD

**Issue by PurpleDerg** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#181]
Run Mutation tests for the code utilizing Jest for react native. 
Running mutation tests entail: 
-Statement Mutation -> Statements are deleted or replaced with a different statement 
                                       Ex:  statement "A=10 by B=5" is replaced with "A=5 by B=15."
-Value Mutation -> Values are changed to find errors. 
                               Ex:  "A= 15" is changed to "A= 10" or "A=25."
-Decision Mutation -> Arithmetic or logical operators are changed to detect errors.
                             Ex: "(A<B)" is changed to "(A>B)."
This task will be considered done once the tests have been created, ran, and reported to the documentation alongside screenshots detailing the process and how it works. 

Diff: 4
Priority: 4

 https://jestjs.io/docs/tutorial-react-native
https://www.techtarget.com/searchitoperations/definition/mutation-testing

**Comment by PurpleDerg** [comment]
Gonna be needing to create dummy or quick unit tests using jest, and then installing stryker to then perform the mutation testing. 

Since mutation testing is done primarly to test, if one's testing is sufficient to detect changes in code. 
Is there a person that is working with unit testing, or already an issue with it that I can ask about their unit testing

**Comment by irsaris** [comment]
Hello, this is missing in the document (@PinkSylvie for visibility).

**Comment by PurpleDerg** [comment]
Hi yes, I'm unsure what to put into the document as issue #180 already put a lot of what this one was gonna be

**Comment by irsaris** [comment]
I see, then just make sure that nothing is missing and @ me again when you are done

**Comment by PurpleDerg** [comment]
added my part on mutation testing on 4.9 on documentation. Additional mutation testing on the document
