### ISSUE TITLE
Implement " permanent data Storage" locally

### ISSUE THREAD

**Issue by PurpleDerg** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#185]
Reading upon this, this would utilize "AsyncStorage", a dictionary module that lets data be stored locally throughout the app. 

This task would be considered done, once the library is imported.
- it should be tested that it can hold data within the app even if it closes and opens. 
- should hold the attributes of the current User, and Pet class. 
- it should be able to retrieve said attributes on a Function call if installed succesfully. 

Diff: 4
Prio: 4

**Comment by irsaris** [comment]
@PurpleDerg would this task be doing both of these or just one?
- Implement data permanence so the user doesn’t lose their pet, study set and progress, when the app closes
- Implement the User Object (keeping data of everything, care mistakes, etc)

**Comment by PurpleDerg** [comment]
Adding data permanence would mean adding the means to allow all of that data to be kept locally . 

Things like adding care mistakes would still need to be saved to the "local storage"

**Comment by gabrielpadilla7** [comment]
Working together on this issue.

**Comment by gabrielpadilla7** [comment]
making testers for this issue is proving more difficult than expected (at least in my case). If we can't get this to work with the testers, we'll have to manually test everything

**Comment by irsaris** [comment]
I see, thank you for updating about this issue, hope it goes well.

**Comment by PurpleDerg** [comment]
Working on bugs from the implemented asyncstorage of the indivual classes.

**Comment by irsaris** [comment]
Alright
