### ISSUE TITLE
Record Voiceovers for Video Presentation

### ISSUE THREAD

**Issue by Adhel-Esteban1** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#186]
Produce a professional and engaging voiceover to accompany the PowerPoint presentations for the milestone. Follow these guidelines to ensure a compelling presentation:

Script Preparation:

Develop a clear and concise script that aligns with the content of the PowerPoint slides.
Ensure the script covers key points, explanations of visual elements, and any additional insights that enhance understanding.
Aim for a conversational tone to maintain audience engagement.
Voiceover Recording:

Utilize high-quality recording equipment and a quiet environment to achieve clear audio.
Record the voiceover in a natural and confident manner, emphasizing key concepts and transitions.
Pay attention to pacing, allowing listeners to absorb information without feeling rushed or overwhelmed.
Synchronization with Slides:

Coordinate the voiceover timing with the PowerPoint slides for seamless integration.
Ensure that the narration complements the visual elements, providing a cohesive and immersive experience.
Always make sure to leave at least 3 seconds of silence before and after each slide. This will simplify the process for the editor.
Say "next slide" every time you change a slide so the editor can time what you are saying.
Share the audio/video with editor

This can be done with Google Drive for simplicity.

**Comment by PinkSylvie** [comment]
Hello! I'm sending this here so that it can be linked to this task. The professor had commented on the length of the video last milestone and how the test plan could have been discussed so I'm sending you here the link to this milestone's test plan. It details all the testing that should be done for this milestone: https://docs.google.com/document/d/11XNndPtC92lRqi7hvZ5HUpybQiGk2l02SFMnEeYmBVI/edit?usp=sharing

**Comment by Adhel-Esteban1** [comment]
@PinkSylvie Thanks for sharing this test plan, I will be sure to cover it in detail! So, just to clarify, this would go on the final part of additions to documentation where we cover "Lecture Topics", and since this one is a bit longer, I assume I must go in more detail here, yes?

**Comment by PinkSylvie** [comment]
I don't recommend all of it, since it is a bit of a lot. But what you think are the most important parts of it, for example the testing that was assigned for us to do in the Moodle milestone 2 instructions and what came out of them.

**Comment by Adhel-Esteban1** [comment]
Understood! I'll take a look at the criteria and cover the most important parts.

**Comment by irsaris** [comment]
Will be closed with the promise of it being completed before the deadline next week.
