### ISSUE TITLE
[Lecture Topic Task] Make some scripts so Scripted Testing can be done to test the Pet

### ISSUE THREAD

**Issue by Ryan8702** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#187]
Testing is repeatable; the test cases can simply be run again thus providing good auditability for verification and validation activities.

Scripted test cases can be explicitly traced back to requirements allowing test coverage to be documented in a traceability matrix.

Tests cases can be retained as reusable artefacts for the current and future projects, possibly reducing the time required for future Test Design and Implementation.

**Comment by irsaris** [comment]
Hello, please suggest urgency and difficulty scores.

**Comment by Ryan8702** [comment]
Have to research the Pet aspect of the code and ask every member so I can make standardized scripts that can work with any changing of the code to see that the base code has not been altered too much and still work like they worked before.

Suggest: 
Difficulty - 6+
Urgency - 4+

**Comment by irsaris** [comment]
Update on this?

**Comment by Ryan8702** [comment]
@irsaris task complete
