### ISSUE TITLE
Implement selectable number of flashcards

### ISSUE THREAD

**Issue by AnthonyMed13** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#19]
For this task you need to create a component that allows you to select the number of flashcards that you want to study inorder to be able to control how much food you give to the pet.

This way you will not have to study a lot to feed the pet. If your pet is nearly without food you can select to study more flashcards to fill his hunger bar completely.

This may need some revising any suggestions would be appreciated

**Comment by PinkSylvie** [comment]
Oh dear, pet difficulty decides the amount of cards that are used

**Comment by PinkSylvie** [comment]
@irsaris

**Comment by irsaris** [comment]
I see, no worries your task will be marked as completed @AnthonyMed13
