### ISSUE TITLE
[Lecture Topic Task] Black Box testing for the Pet

### ISSUE THREAD

**Issue by Ryan8702** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#190]
Test functional units by verifying that they output expected values given specific inputs.

**Comment by irsaris** [comment]
Hello, please suggest urgency and difficulty scores.

**Comment by Ryan8702** [comment]
Have to verify most aspects that can produce outputs and show that the expected output is the one that we are getting to show that we have made no coding errors.

Suggestion:
Difficulty - 4+
Urgency - 4
