### ISSUE TITLE
[Lecture Topic Task] Perform White-box testing on the Pet

### ISSUE THREAD

**Issue by Ryan8702** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#191]
Relies on the analyzing the code itself and the internal logic of the software.

**Comment by irsaris** [comment]
Hello, please suggest urgency and difficulty scores.

**Comment by Ryan8702** [comment]
Due to it depending on one sitting down and analyzing the entire Pet code and the internal logic of the Software being used to perform the testing. 

Suggestion:
Difficulty - 6+
Urgency - 4

**Comment by irsaris** [comment]
In which section is this in the documentation?

**Comment by Ryan8702** [comment]
@irsaris 
it is a task dependent on analyzing the code itself and the software there is nothing to be added to the doc, it can just reference other test cases made to see that the code was implemented successfully

**Comment by irsaris** [comment]
I see, could you at least mention it somewhere in the documentation?
