### ISSUE TITLE
Fix scrolling for Testing the app on Web

### ISSUE THREAD

**Issue by gabrielpadilla7** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#192]
![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/93553908/8b94bd0c-a38d-4a8c-9941-4480930779b8)
The app is having issues handling scrolling when the desktop doesn't have enough space to handle it all. To complete this task, the app when testing on web should be able to scroll down on all the screens

**Comment by misaelmercado1** [comment]
limited scroll functionality added for stats page. waiting for pull requests.
