### ISSUE TITLE
Implement Care Difficulty

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#198]
When a Pet is Created the user decides a care difficulty. Based on this care difficulty the app will decide how many cards will the user study every time they do a care action. For example:  If a pet was created with a study set of 9 questions if the user picked a difficulty of - 
Easy - 1/3 of questions (3 questions) 
Intermediate - 2/3 of questions (6 questions)
Hard - 3/3 questions (9 questions)

Implement an algorithm that changes the amount of cards run for each minigame based on the difficulty chosen.

To complete:
You'll have to show how based on the difficulty chosen by the player the minigames would run a different amount of cards for each difficulty

**Comment by Elielh17** [comment]
I would suggest:

Difficulty: 4
Priority: 4

**Comment by Elielh17** [comment]
Implemented algorithm that depending on the difficulty sets the number of questions to answer to a certain number. Easy - 1/3 of questions (3 questions), Intermediate - 2/3 of questions (6 questions) and Hard - 3/3 questions (9 questions). The questions are chosen randomly from the array of questions. If there are less than 9 then the number of questions is sliced case "easy": fraction = 1 / 3, case "medium": fraction = 2 / 3, case "hard": fraction = 1

![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/70725243/d5a75747-8fe3-4868-9c97-01aa6bd7987c)

![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/70725243/641e5e05-f295-4d04-8f52-f8e90f4b5731)


![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/70725243/1479da84-7409-470d-bdc8-bff2f10cf7da)

![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/70725243/a9ba1afc-4243-49f4-9a84-7b91078dc521)
