### ISSUE TITLE
Implement Study Set Creation at Pet Creation

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#199]
After a pet is created the study set associated with the pet will be created as well. In this task you'll implement a screen that will follow up after the pet creation screen to create flashcards and these flashcards created must be reflected in the Flashcards overview screen

To complete: You must show how after the pet creation screen, the study set creation screen is triggered and how the cards created here are reflected in the flashcard overview screen

**Comment by irsaris** [comment]
@JeremySanchez1 please suggest scoring
