### ISSUE TITLE
[Lecture Topic Task] Sketch UI

### ISSUE THREAD

**Issue by Adhel-Esteban1** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#2]
In order to have a solid foundation, we need a sketch of the UI. This can be hand written, the actual mockup comes later. A sketch is necessary to have a grasp of what we are building, and what will be required. No colors, just a hand-drawn idea. A good sketch of the main page, and the buttons and their location, and the other screens that will appear on the UI. 

To complete:
Get sketches approved by team and managers, add a pdf document with the sketches to the project google drive and add link to it in issue comment. 

Marianyelis' Note:

I made the sketches already so I am taking this task. Without the sketches, no design can be made and as such no design can be tested. Reason why the UI Sketches are a stepping stone to be able to do tests for the design and this is a Lecture Topic Task.

**Comment by irsaris** [comment]
Access has been updated.

**Comment by PinkSylvie** [comment]
@irsaris Sending the sketches link here to review: https://drive.google.com/file/d/1dOwMVHcT75rP7rx6-aPtPXErtThAR0O1/view?usp=drivesdk
Even tho the sketches where done already and shown to the team I am referencing here design and implementation tasks that could need the use of the UI sketches for their tasks: 

#95,#41,#82,#46,#78,#38,#36,#10,#93,#80,#70,57,#41,#75
