### ISSUE TITLE
Implement Death Conditions

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#200]
Following up after task #151, implement the conditions to trigger the death sequence. A pet will die after 10 death mistakes and the pet will change to its death animation/design. When the user taps the screen it must give the user the option to replace the dead pet with a new one and store the data of the one that just died into the user's pets data to show in the "My Pet's" Screen

To complete:
Be able to trigger the death sequence after 10 care mistakes, make the pet's animation change after the death was triggered, that the only thing the user can do is create a new one and that the data of the pet that just died is stored in the user's My Pets Screen

**Comment by Elielh17** [comment]
I would suggest:

Difficulty: 4
Priority: 4

**Comment by Elielh17** [comment]
![Screenshot 2024-03-19 135957](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/70725243/400c471c-5248-4222-ab99-e3ada2670c02)

After 10 Care mistakes the death animation is triggered and the navigation buttons are disabled, except the "My pets" page, to only let the user create a new pet.

**Comment by Elielh17** [comment]
https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/commit/7f0864aa1e18f345ab824bf3ca0beab1f608af5a
