### ISSUE TITLE
[Lecture Topic Task] Implement and run Soak testing

### ISSUE THREAD

**Issue by AnthonyMed13** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#220]
Soak is a type of performance evaluation for software. It involves testing a system with a typical workload over a prolonged period to identify performance issues that might emerge over time. This kind of testing is crucial for uncovering memory leaks, resource leaks, and other slow-building problems that might not be apparent during shorter, more conventional testing periods.

Since the main goal of the application is to help students study, the application needs to be tested in order to ensure that long study sessions won't be a problem. 

(This is for milestone 3)

Tentative points:
Urgency: 4
Difficulty: 2

**Comment by AnthonyMed13** [comment]
I added this to the documentation if you could verify it to close the issue @PinkSylvie @irsaris

**Comment by PinkSylvie** [comment]
Pull request?

**Comment by AnthonyMed13** [comment]
> Pull request?

For this task I ran an macro key setup to use the website for a total of 8 hours so there was no code to be added to the repository

**Comment by PinkSylvie** [comment]
Just read it and it looks great!
