### ISSUE TITLE
[Doc Feedback] Fix Domain Narrative

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#232]
"The domain narrative is supposed to narrate how the domain fits together. What does that mean? In your project, you can describe how the various concepts that you identified interplay with one another. Think about what you want to say about the domain (based on what the stakeholders told you). For example, you might want to talk about what "exam preparation" is: as in "when a student studies in order to know answers to questions and problems that they expect to appear on an exam". Or, you can narrate "an exam is a collection of questions and problems that a student needs to answer as an evidence that they have understood and are able to apply skills and knowledge. On some exams the only distinction is whether the student passed or failed the exam, on others the student gets a grade to indicate how well they did. When preparing for an exam a student will usually use different learning techniques. Learning techniques differ in how well they are suited to achieve different outcomes. For example, spaced repetition is considered a good technique for learning knowledge, while doing sample problems is good for learning skills...". In a way the narrative relates to the terminology, the terminology gives the definitions of the individual terms, but the narrative tells a story how they interplay."

Fix the domain narrative of our documentation while following along the professor's feedback mentioned above

**Comment by Adhel-J** [comment]
@irsaris @PinkSylvie can you please check this task

**Comment by PinkSylvie** [comment]
The professor mentioned how the narrative is supposed to show how things in the terminology connect with each other but I dont see that connection added nor much narration regarding the terms like the professor mentioned

**Comment by PinkSylvie** [comment]
I do see a couple of them tho like student, procrastination, studying, but I do believe the professor would like to see the ones he mentioned as well

**Comment by Adhel-J** [comment]
ok, I'll fix that

**Comment by Adhel-J** [comment]
@irsaris @PinkSylvie check again

**Comment by PinkSylvie** [comment]
You removed the whole narrative instead of editing it to include narratives for the terms mentioned by the profesor. The professor didnt say our whole narrative was bad. Just that there wasnt much narrative regarding our terminology terms

**Comment by Adhel-J** [comment]
The current narrative mentioned things that were outside of the domain narrative that the project is going to fix, it mentioned the transition from high school to university, which is unnecessary in my opinion, as the app is focused on university students, although it could be.

**Comment by Adhel-J** [comment]
restored the previous narrative, can you tell me what you think of the whole narrative

**Comment by PinkSylvie** [comment]
I believe you should merge concepts mentioned in the old narrative with what you wrote. What you wrote is fine but it eliminates narratives done by the previous one by erasing it. There's no reason to erase everything when just adding the narratives requested by the prof would've sufficed

**Comment by Adhel-J** [comment]
merged the two ideas, check again, let me know if there is anything I need to fix

**Comment by PinkSylvie** [comment]
Looks good! Great work!
