### ISSUE TITLE
[Lecture Topic Task] (Doc Feedback) Expand our explanation of the load tests done

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#233]
"Since the expected loads are missing, so it the relation of the setup to such expectations."
"You show a screenshot of JMeter with some green checkmarks, but what are the load tests that passed and what are those that failed? What can you conclude from your results?"

The professor wanted for:
- The project discusses and explains their load testing setup and how it relates to their expected load
- The project interprets the load testing results they observe

No explanation was given on the relation of the setup to the expectations  and no conclusions were given on the results of our load tests. 

Make sure to add them to the documentation

**Comment by Fabian-J** [comment]
Changes were added by Jonathan to show expected loads and show relation between tests and expected loads.

**Comment by irsaris** [comment]
Does that mean that you didn't contribute anything new to the section?

**Comment by Fabian-J** [comment]
Jonathan covered everything so I don't see what I could add.

**Comment by irsaris** [comment]
So what do you suggest we do with this task if no work was done ?

**Comment by Fabian-J** [comment]
Work was done but it was done by Jonathan. I suggest assigning them to this task and for them to get the points.

**Comment by irsaris** [comment]
You only have this and one other task though, i suggest you dm me to see what we can do about this.
