### ISSUE TITLE
 [Doc Feedback] Fixes regarding function signature, behaviors and events

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#234]
"There is no reason to have a separate section domain events, actions, behaviors, and function signatures when you already have a section for the terminology. A "term" that your project needs can be of any kind: whether entity, action, event, or behavior. As a matter of fact, whether you consider something e.g. as an action or as a behavior might change depending on the level of abstraction you are currently interested in. Whether you talk about a "study session" (entity), "studying" (action), "studying - ... made up of a sequence of actions and events" (behavior), or "having just finished studying" (event), these all need to be clearly defined as terms and the place to do this is the terminology. Since your function signatures abstract some specific aspects of the actions, they too belong in the terminology together with the actions they help clarify.

To be domain behaviors the actions as well as the events that make these up will themselves be domain actions and domain events. They will therefore not involve any reference to the system-to-be. So, logging into the system, being a "user" etc. do not make sense here. The behaviors that you provide are behaviors, but they are not domain behaviors, but usage behaviors or interaction scenarios.

The reviewing of the study material with the flash card system is not visible in the function signature "RecordStudyProgress". You also need to check your other actions."

Follow up on the descriptions mentioned above by the professor to fix those details in the docuementation:

- Add the domain events, actions, events, and behaviors into the terminology but make sure to have someway to identify what are they as well be it an, action, event, term, function signature etc.
- Fix the function signatures as mentioned by the professor
- Eliminate references from the system to be from the behaviors, actions and events
- Follow on each of the professors complaints mentioned above

**Comment by JorgeC08** [comment]
Updated the documentation to integrate domain events, actions, behaviors, and function signatures into the Terminology section as requested in the feedback. Removed system references from domain-specific elements and clarified function signatures to focus on domain interactions.

**Comment by PinkSylvie** [comment]
You removed most of the function signatures and events instead of editing them to add them into the terminology

**Comment by JorgeC08** [comment]
Hello @PinkSylvie. I asked for your approval via discord but I’ll send it here.

I will modify sección 2.1.5 with this:

2.1.5 Domain Event, Actions, Behaviors, and Function Signatures
To better our comprehension of user interactions and system responses of Study Pet, it is crucial to determine a clear distinction between events, actions, and behavior. This will aid in building a robust and intuitive user-friendly interface that facilitates the study and pet interaction processes.
Behaviors:
Terminology:
* Pet Interaction: User's engagement with their virtual pets, including feeding, playing, and cleaning.
* Study Session Management: User sets up flashcards to study and influence the development of their study pet.
* First-time Engagement: User starts navigating the app and setting up their account.
* Engagement with Study Sessions: User reviews study materials using a flashcard system.
Domain Events:
* Pet's Health and Happiness Changed: Pet's health and happiness levels increase or decrease based on user's interactions.
* Flashcard Set Created: A new set of flashcards is ready for use.
* Study Session Scheduled: A study session with specific details is scheduled.
* Study Progress Recorded: User's study progress for a specific course is recorded.
Domain Actions:
* Initiate Pet Care: User begins a pet care session by engaging in activities that promote pet health and happiness.
* Neglect Pet Care: User does not log in and neglects pet care.
* Create Flashcard Set: User creates a new set of flashcards for a specific course.
* Schedule Study Session: User schedules a study session with specific details.
* Review Study Materials: User reviews created study materials with a flashcard system.
Domain Behaviors:
* Pet Care: Sequence of actions and events related to caring for a virtual pet, including feeding, playing, and cleaning.
* Study Session Preparation: Sequence of actions and events related to creating flashcards and scheduling study sessions.
* Studying with Flashcards: Sequence of actions and events related to reviewing study materials using flashcards.
Function Signatures:
* UpdatePetCare(Pet) -> Pet
    * Updates the pet's health and happiness levels based on the user's interactions.
* CreateFlashcardSet(Course) -> FlashcardSet
    * Creates a set of flashcards for a specific course.
* ScheduleStudySession(StudySessionDetails) -> StudySession
    * Schedules a study session with specific details.
* RecordStudyProgress(Course, StudyDuration) -> CourseProgress
    * Records the study progress for a user in a specific course, updating the progress database.

**Comment by PinkSylvie** [comment]
Did you? And also arent the actions and events missing?

**Comment by JorgeC08** [comment]
> Did you? And also arent the actions and events missing?

Got out of work and I'm currently working on it.

**Comment by irsaris** [comment]
hi, has this been completed?

**Comment by JorgeC08** [comment]
I added all the corresponding modifications. To my understanding, yes, it is completed.
________________________________
