### ISSUE TITLE
[Lecture Topic Task] (Doc Feedback) Add a typical usage scenario for load testing in the documentation

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#235]
"What is the typical usage scenario for load testing?"

In the appropriate section of the documentation add the typical usage scenario for load testing. As in what is the typical usage scenario in the project that we have been using load testing for.

**Comment by JonathanDebug** [comment]
I have added the typical usage scenarios for load testing. Check when possible.

**Comment by JonathanDebug** [comment]
@irsaris
