### ISSUE TITLE
[Lecture Topic Task] (Doc Feedback) Make sure the project discusses plausible load expectations

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#236]
"What are the expected loads? Why do you expect such a load? Not more, not less?"

The above was the professor's feedback on the load expectations discussed in the documentation. Expand the load expectations in the documentation so that they answer the questions mentioned above.

**Comment by JonathanDebug** [comment]
I have added expected loads to the documentation. Please revise. @irsaris
