### ISSUE TITLE
[Lecture Topic Task] (Doc Feedback) Fix our project's use of Hoare logic 

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#237]
"Your attempt at using Hoare logic in this way does not seem to work. If all else fails you could still use assertions as a run time approximation of pre- and post-conditions."

It seems our use of Hoare Logic Testing isn't working properly. Fix it so that it runs properly or as the professor mentioned in their feedback comment - use assertions as a run time approximation of pre- and post conditions. Then document your results in the documentation

**Comment by JeremySanchez1** [comment]
@irsaris @PinkSylvie Pinged for documentation verification. The section has been modified.

**Comment by PinkSylvie** [comment]
Pull request, the task required implementation to fix the hoare tests so they would run and work

**Comment by PinkSylvie** [comment]
Did you update the documentation as well with the working results?
