### ISSUE TITLE
[Lecture Topic Task] (Doc Feedback) Fix our use of types in the documentation

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#238]
"In your application of types you want to introduce types in such a way that they make it impossible to commit certain kinds of errors. So, for example, you would introduce an opaque type, say, "Happiness" which might be defined as a synonym for int or, if your programming language permits, might also be defined as a range type 0-100. But the important aspect would be that it's opaque and so values of the new type cannot be compared, assigned, or otherwise about used where ints are required. This is just the start of what you could do here. Review the discussion of types from the lecture."

The professor gave a lengthy description on the things he disapproved. Fix our type usage according to his description and further review of the lecture slides.

The professor wanted for the project to: 
"The project uses types to communicate insights about their functions and enhance understandability e.g. by introducing meaningful types to represent domain concepts such as Student, Course, or Doctor, Appointment, etc.generates candidate resolutions using further elicitation as well as using the resolution tactics."

**Comment by JonathanDebug** [comment]
Changes added, please revise.
