### ISSUE TITLE
[Doc Feedback] Fixes regarding requirement complaints

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#239]
""The application must provide means to present the well-being values of the pet, both happiness and hunger." The presentation sounds much more like an interface requirement: there's data inside the system-to-be that needs to be reflected back into the domain. But a related domain requirement is that the system-to-be must associate a happiness and a hunger value with each pet. The other domain requirements also need to be reviewed: do they really target only the domain? Or do they mix domain and interface aspects together? For example, generating flash cards is not purely a domain requirement since "generating" seems to involve quite some interface concerns. If we think about all the concerns involved we can discover several domain and several interface requirements. The system-to-be must associate a question and an answer with every flash card (domain requirement). The system must provide means by which the association of the question to a flash card can be updated (still domain...). The system must provide a form through which a user can edit a question to be associated with a flash card. This form must consist of a text field and a cancel button and an accept button. (interface). These are just examples to illustrate splitting up the requirements, they are not meant to be the actual requirements you should use.

"The app must be optimized for screen sizes..." this is a difficult requirement: what does optimized mean? How do you know that you achieved the requirement? What is the criterion that you expect an end user to apply?

The requirement on the user profiles: is that understood to refer to the storage capacity? You might also want to give a brief estimate on how much storage we're actually talking about here.

Why does the discussion of the flash card implementation under the heading "... back-end" have so many front-end aspects in it?"

The professor gave several complaints regarding our requirements, follow up on his complaints and fix those details in the documentation

**Comment by JeremySanchez1** [comment]
@irsaris @PinkSylvie Pinged for documentation verification. These sections have been modified.

**Comment by PinkSylvie** [comment]
The requirement changes seem to be saying the same thing just with different wording

**Comment by JeremySanchez1** [comment]
Most were placed correctly in their sections, but their wording implied some connection to other types of requirements. For example, in domain requirements saying “provide a means… for the user” implies some type of interface functionality. So for specificity most of the changes were wording. Those that were cut or added more details, either didn’t belong at all to thats sections or the requirement was very loosely defined and needed more explicit descriptions. This was the case for the machine requirement of how much storage was needed for the app, or how the screen dimensions should change per device and model.

**Comment by PinkSylvie** [comment]
I'm mostly worried for the domain requirements

**Comment by JeremySanchez1** [comment]
Could this be elaborated further? @PinkSylvie

**Comment by JeremySanchez1** [comment]
Re-checked to ensure there’s no overlap between domain/interface requirements. @PinkSylvie
