### ISSUE TITLE
[Doc Feedback] Fix Needs

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#241]
"You still mention the study pet APP in the needs, but just barely... There are two things going on here: 1) you're summarizing the needs (study-centric, effective, fostering supportive and engaging learning experience) and 2) you present a first idea on how you want to satisfy the needs (which, of course, belongs into the ideas section)."

Eliminate the mention of the app in the needs as that's part of our system to be and the our needs are those that the app will resolve once it finally exists.

**Comment by Adhel-J** [comment]
Please check if the mention of the app and its fixes are okay.

**Comment by PinkSylvie** [comment]
They refer to the project but project cold easily be replaced for app. The domain isn't the project either. The domain is the situation in which something like our app would be needed

**Comment by Adhel-J** [comment]
@PinkSylvie @irsaris Check again when you are able

**Comment by PinkSylvie** [comment]
You erased the whole needs section instead of editing the details mentioning the app/project to comply

**Comment by Adhel-J** [comment]
The criteria states that you cannot mention the application that is needed to fix the problem

**Comment by Adhel-J** [comment]
"For example, in a project improving the situation with people
    having too many calendars "the tool should direct all the tasks and
    events into one single place" is not a need." 
This is taken from the criteria that the professor did

**Comment by PinkSylvie** [comment]
That doesnt mean erase everything unless you are going to replace it with something equally as susbtantial

**Comment by Adhel-J** [comment]
restored the previous needs, can you tell me what you think

**Comment by PinkSylvie** [comment]
I think what you had made the correct change of eliminating the mention of the app or project. Blending what you had with what was already there would make the needs perfect

**Comment by Adhel-J** [comment]
merged the two ideas, sorry for the long wait

**Comment by PinkSylvie** [comment]
Looks good! Great job!
