### ISSUE TITLE
[Lecture Topic Task] make Unit Test for the database, to ensure that the database is storing and loading values accordingly

### ISSUE THREAD

**Issue by PurpleDerg** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#244]
After setting up database, making unit tests in order to make sure that the proper data is being stored and loaded

This Lecture Topic Task is dependent on the issue #242

Suggested Difficulty: 6
Suggested Priority : 4

**Comment by gabrielpadilla7** [comment]
Testing has been done. The tests include the schema correclty being defined, and the reading, writing and deleting process working correctly. 

Previous tests, some HAVE BEEN BROKEN when there was a merge from main to the DB branch, meaning that somewhere the tests were broken/outdated.
