### ISSUE TITLE
Add Derived Goals  to the documentation

### ISSUE THREAD

**Issue by Ryan8702** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#25]
- Identify derived or secondary goals for the project and include them in the documentation. It should be the last subsection of the Informative section

"Your primary project goal is described by the other sections: current situation, needs, ideas, … Here you talk about secondary desirable outcomes. These should be substantially different from your primary goals and not just reiterations of those primary goals. For example, a project concerned with beach quality monitoring might have as its primary goal to give information about the cleanliness of the water and the beach to beach-goers. A secondary goal could be to increase tourism to some lesser known beaches or to raise awareness among the public about the need to keep the beaches clean."

Suggested points → Priority(Medium) * Difficulty(Medium) = 4 * 4 = 16

**Comment by PinkSylvie** [comment]
Hello! I see this part of the documentation is missing, would just like to remind you that tasks are due tomorrow so that we have Friday for review and so that we are able to turn the documentation in.

**Comment by FrancesC8** [comment]
@irsaris @PinkSylvie I completed the task and added the contents to the documentation.

**Comment by PinkSylvie** [comment]
> @irsaris @PinkSylvie I completed the task and added the contents to the documentation. 

Just checked! Nice work 👍
