### ISSUE TITLE
[Lecture Topic Task] TDD: Continue to perform and document unit tests on new StudyPet components, implementations and features.

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#258]
Previous tests were performed on developing environment and flashcard components. As new features are implemented, unit tests must be carried out in order to ensure functionality and quality. These tests are documented thoroughly, step-by-step, with explanations added for every iteration, albeit success or failure; for the betterment of the team and the project as a whole.

Suggested Difficulty: 6
Suggested Urgency: 6

*As feature development progresses, further understanding of code and the domain is necessary, so I recommend a difficulty raise for assignees sake (+3 from previous milestone).

**Comment by PinkSylvie** [comment]
Tests on what? Please be specific otherwise we might end up having multiple people doing the same test on the same thing?

**Comment by DiegoLIRodriguez** [comment]
Specifically new Flashcard Components and Features:

- Difficulty selection and its impact
- Happiness and hunger balancing
- Study set completion and deletion
- Any other milestone 3 features

**Comment by DiegoLIRodriguez** [comment]
New features tested and documented here: https://docs.google.com/document/d/1OVempeF9_xd6mF7KFI6mCLDUOdY0dyVFXkLZH5gOtMg/edit

**Comment by PinkSylvie** [comment]
I dont see what you added in the changelog. What section did you added it in as well?

**Comment by DiegoLIRodriguez** [comment]
My bad! It's the fifth case tests in TDD. Added the changes to the log.

**Comment by PinkSylvie** [comment]
Did you merge this branch already or create a pull request for it?

**Comment by PinkSylvie** [comment]
But I saw the section and it looks quite nice

**Comment by irsaris** [comment]
@DiegoLIRodriguez PR?
