### ISSUE TITLE
[Lecture Topic Task] Usability Testing Implementation

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#259]
"the team conducted at least one usability
    study. They identified a a few meaningful usability questions or
    test objectives for at least one task that is valuable for their
    target audience. For example, "how many of our students will be able
    to enroll into all their courses for the next semester with our
    system without having to consult any help screens in at most 15
    minutes?" 

Implement Usability Testing into the Project according to what was discussed in class

**Comment by FrHend-Raul** [comment]
@PinkSylvie Check this task with #261 for completion

**Comment by FrHend-Raul** [comment]
Tentative score for this one 4 and 4

**Comment by PinkSylvie** [comment]
> Tentative score for this one 4 and 4

It's scored

**Comment by FrHend-Raul** [comment]
@PinkSylvie @irsaris The #260 was closed but this one hasn't, I need more in the documentation for this and the #261 to be closed?

**Comment by PinkSylvie** [comment]
Like 260 was closed by github automatically when the branch merged. Sorry for taking a bit to close it, great job!
