### ISSUE TITLE
Add Domain Rough Sketch  to the documentation

### ISSUE THREAD

**Issue by Ryan8702** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#26]
• Rough sketches are unprocessed, often containing a lot of specifics. The concept analysis goes over the rough sketch and abstracts out meaningful concepts that help structure the specifics in the rough sketch. Based on this you then write the narrative.
  • Rough sketches are for collecting unprocessed information for example from brainstorming sessions, interviews, literature review, … Your domain description rough sketch looks a bit too processed, what you write might better be placed in the domain narrative.
  • Rough Sketch - seems like a broad version of the terminology, which isn't bad, but it would go in to the narrative section and could go a bit more into how the domain functions and its environment. Rough sketches are for collecting unprocessed information for example from brainstorming sessions, interviews, literature review, … Your domain description rough sketch looks a bit too processed, what you write might better be placed in the domain narrative. The concept analysis goes over the rough sketch and abstracts out meaningful concepts that help structure the specifics in the rough sketch. Based on this you then write the narrative. The reason to make this process explicit is so we can retrace it should our knowledge or perspective change.

**Comment by AnthonyMed13** [comment]
@PinkSylvie I finished and added the rough sketch to the documentation

**Comment by PinkSylvie** [comment]
Could you reference properly using quoting, what did you get from that reference (as in via number or something linking a quote to a reference) maybe IEEE method so that it looks cleaner?

**Comment by AnthonyMed13** [comment]
> Could you reference properly using quoting, what did you get from that reference (as in via number or something linking a quote to a reference) maybe IEEE method so that it looks cleaner?

It should be done now

**Comment by PinkSylvie** [comment]
Looks good then!

**Comment by irsaris** [comment]
@Ryan8702 instead of citing the references at the bottom, could you hyper link them instead?

**Comment by AnthonyMed13** [comment]
> [@AnthonyMed13](https://github.com/AnthonyMed13) instead of citing the references at the bottom, could you hyper link them instead?

Okay i fixed it now

**Comment by irsaris** [comment]
Ok, thanks.
