### ISSUE TITLE
[Lecture Topic Task] Usability Testing Automation

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#260]
Following up on task #259, automate the Usability Tests so that they run the whole test suite with as little setup as possible.

Please review with the professor on how he would like for the automation to be done.
To complete:
Explain how to run the automated tests and show them running and the results

**Comment by FrHend-Raul** [comment]
@PinkSylvie @irsaris  This task has a pr #326, check to close. Details were added to the documentation Usability Testing part.

**Comment by FrHend-Raul** [comment]
PR was merged and the details of this test was added to the documentation in the part 4.12.2

**Comment by PinkSylvie** [comment]
Just read the report,looks great!
