### ISSUE TITLE
[Lecture Topic Task] Property Based Testing Documentation

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#264]
Follow up on tasks #255 and #262 to add all the information of the project's use of property based testing into the documentation.

" Explain their test setup, the choice of test
participants, their monitoring, etc. Also explain their minimal
expectations for considering the system to suffice. Furthermore,
they recommended improvements and draw conclusions from their test
results."

To complete:
As mentioned above add those things to the Milestone 3 document like the rest of the testing methods

**Comment by irsaris** [comment]
remember to mark what was added in green and what was deleted in red and also write in the changelog

**Comment by bally7301** [comment]
ya lo añady all documento porfavor diga si necesita algo

**Comment by PinkSylvie** [comment]
"the choice of test
participants, their monitoring, etc. Also explain their minimal
expectations for considering the system to suffice. Furthermore,
they recommended improvements and draw conclusions from their test
results." You mentioned the setup and the tests but not the results or any answers for the rest of things the profesor asked for

**Comment by bally7301** [comment]
I have added results to this section of the document

**Comment by PinkSylvie** [comment]
Good work!
