### ISSUE TITLE
[Lecture Topic Task] Fuzzy Testing Implementation (on another feature)

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#265]
Fuzzy Testing was already implemented in task #132, so for this task you have to follow up on how they did it to implement further Fuzzy tests on another feature. According to the professor's guidelines: "Similar to property-based testing, the team incorporates
    fuzzing in their project using the approaches described in the
    fuzzing book. In particular, they use fuzzing for testing their web
    interface along the lines of the "Testing Web Applications" chapter." 

We understand that our project isn't a webapp so either discuss with the professor an alternative or follow on the instructions as best as you can.

**Comment by FrancesC8** [comment]
Suggested points -> Priority(Medium) * Difficulty(Intermediate) = 4 * 4 = 16

**Comment by FrancesC8** [comment]
The scope of implementing fuzzy testing in this task will be for the Pet Sleep feature. Test that the proper restriction alerts appear on the Home Screen when the Pet is asleep (and when not).
