### ISSUE TITLE
[Lecture Topic Task] Fuzzy Testing Automation

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#266]
Following up on task #265, automate the Fuzzy Tests so that they run the whole test suite with as little setup as possible.

Please review with the professor on how he would like for the automation to be done.
To complete:
Explain how to run the automated tests and show them running and the results they generate

**Comment by AnthonyMed13** [comment]
@PinkSylvie finished adding the issues and possible countermeasures for automation of fuzzy test if you could check the documentation to close this issue

**Comment by AnthonyMed13** [comment]
Hi, just wanted to check in and see if this issue can be closed @PinkSylvie

**Comment by PinkSylvie** [comment]
Just checked, looks great, good work!
