### ISSUE TITLE
[Lecture Topic Task] Fuzzy Testing Documentation

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#267]
Follow up on tasks #265 and 266 to add all the information of the project's use of Fuzzy Testing into the documentation.

" Explain their test setup, the choice of test
participants, their monitoring, etc. Also explain their minimal
expectations for considering the system to suffice. Furthermore,
they recommended improvements and draw conclusions from their test
results."

To complete:
As mentioned above add those things to the Milestone 3 document like the rest of the testing methods

**Comment by FrancesC8** [comment]
Suggested points -> Priority(Medium) * Difficulty(Intermediate) = 4 * 4 = 16

**Comment by FrancesC8** [comment]
@PinkSylvie @irsaris I added the sections 3 and 4 under TDD - 4.1.4 in the [documentation](https://docs.google.com/document/d/1OVempeF9_xd6mF7KFI6mCLDUOdY0dyVFXkLZH5gOtMg/edit?usp=sharing). This adds documentation for UI testing using Selenium for Pet Sleep feature and Pet Shop page.

I will close the issue to mark it as done.
