### ISSUE TITLE
[Lecture Topic Task] Implement BDD Tests for Pet Emotions

### ISSUE THREAD

**Issue by benjaminCMD** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#270]
Following up w/#177 and #182, implement and run BDD tests for the pets emotion feature.

**Comment by benjaminCMD** [comment]
I'm having issues cucumber for BDD. Not sure if it's just my setup, or if the cucumber framework is not working in general. If someone can let me know, I would appreciate it

**Comment by PinkSylvie** [comment]
PR?
