### ISSUE TITLE
[Lecture Topic Task] Document BDD Testing for Pet Emotions

### ISSUE THREAD

**Issue by benjaminCMD** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#271]
Once the pet BDD tests for the pet emotions are implemented and run, then put into the documentation.

**Comment by benjaminCMD** [comment]
Even though it's not working as intended, I have added everything I've done so far in BDD testing has been added into the document

**Comment by irsaris** [comment]
i think you can also put section 4.18 as a subsection of 4.2 since youre talking about Pet Emotions in both

**Comment by benjaminCMD** [comment]
It has been modified as subsection for BDD

**Comment by PinkSylvie** [comment]
Saw it, looks good!
