### ISSUE TITLE
slideshow presentation

### ISSUE THREAD

**Issue by Adhel-J** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#276]
Create a PowerPoint presentation to complement the video presentation made for the overall accomplishments of the milestone.

**Comment by PinkSylvie** [comment]
Please suggest scoring for your tasks and take into account the lecture topic tasks you need to complete

**Comment by Adhel-J** [comment]
the same scoring that was given to the ones for last milestones

**Comment by irsaris** [comment]
closing task under the promise of it being completed before Monday class.
