### ISSUE TITLE
[Lecture Topic Task] add Load Tests with moncky testing  to other areas features

### ISSUE THREAD

**Issue by bally7301** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#278]
Through specialized testing software, load testing places a simulated “load” or demand on your web application to ensure it remains stable during operation.
For the task, it needs to implement load testing for other features that aren't tested this way and add them to the document. This monkey testing is done via random testing by providing random inputs to test the behavior of the application.  with this, you will check the behavior of the application. for this will take base on the Qcards and the pets actions in the main area of the app.
4x4

**Comment by PinkSylvie** [comment]
Load Based testing on what? Your description is too vague and if you don't specify someone that did could end taking everything

**Comment by bally7301** [comment]
the tit has been updated and the explanation has more details

**Comment by PinkSylvie** [comment]
Did you add new tests? I was reading the section and it all seems to be the same tests that you ran last milestone

**Comment by bally7301** [comment]
yes i have done it a lot of sorting between them but ill add the images soon and a explination

**Comment by bally7301** [comment]
ya lo añady all documento porfavor diga si necesita algo

**Comment by PinkSylvie** [comment]
Pull request? And I don't see that you added any new tests, I see that you added more text on tests previously done in milestone 2, when you said you would run new ones

**Comment by PinkSylvie** [comment]
Nvm the pull request but still on the new tests. We don't need more than one test the same way on the same thing
