### ISSUE TITLE
Add Narrative  to the documentation

### ISSUE THREAD

**Issue by Ryan8702** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#28]
• The domain narrative tells the story of the domain. The domain is that part of the universe of interest to your project but independent of the system-to-be. So, "When a student enrolls into a course, the student has this course for the running semester unless the student drops the course." could be part of the domain narrative, but anything talking about the "application" is not part of domain narrative.
  • The domain is that part of the universe that is of interest to your project, but independent of any system-to-be. Therefore, "home page", "navigation bar" etc. have no place here. You can describe these where you start talking about the actual implementation. Also, in domain narrative you want to talk about the _domain_ not about using the application.
  • Narrative: Again, you're talking about the app that you will create, not the domain. The narrative is supposed to tell you how the domain currently works without your project and is a more elaborate version of your sketch.
  • The first paragraph of the domain narrative talks about the necessity to understand but not about the domain itself. It's valuable, but should be placed somewhere else.
  • The domain narrative is similarly not concerned with the platform, application, or system-to-be. You start with the creation of an event in the application that will notify all users that the creator of said event selects. Then the third paragraph talks about how the team plans to implement this. Implementation is also not part of the domain.

**Comment by PinkSylvie** [comment]
Hello! I see this part of the documentation is missing, would just like to remind you that tasks are due tomorrow so that we have Friday for review and so that we are able to turn the documentation in.

**Comment by Ryan8702** [comment]
@PinkSylvie , @irsaris 
verify

**Comment by PinkSylvie** [comment]
I can't see it in the document
