### ISSUE TITLE
Record Voiceovers for Video Presentation for Milestone 3

### ISSUE THREAD

**Issue by Adhel-Esteban1** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#283]
Produce a professional and engaging voiceover to accompany the PowerPoint presentations for the milestone 3. Follow these guidelines to ensure a compelling presentation:

Script Preparation:

Develop a clear and concise script that aligns with the content of the PowerPoint slides.
Ensure the script covers key points, explanations of visual elements, and any additional insights that enhance understanding.
Aim for a conversational tone to maintain audience engagement.
Voiceover Recording:

Utilize high-quality recording equipment and a quiet environment to achieve clear audio.
Record the voiceover in a natural and confident manner, emphasizing key concepts and transitions.
Pay attention to pacing, allowing listeners to absorb information without feeling rushed or overwhelmed.
Synchronization with Slides:

Coordinate the voiceover timing with the PowerPoint slides for seamless integration.
Ensure that the narration complements the visual elements, providing a cohesive and immersive experience.
Always make sure to leave at least 3 seconds of silence before and after each slide. This will simplify the process for the editor.
Say "next slide" every time you change a slide so the editor can time what you are saying.
Share the audio/video with editor

This can be done with Google Drive for simplicity.

**Comment by PinkSylvie** [comment]
Hello! Sending in again the test plan of this 3rd milestone tests so you can have an idea of what they are and who is working on them so you can reach out to them to know even more about the tests they worked on before talking about them in the presentation: [Test Plan](https://docs.google.com/document/d/1DlhwQ0m6wYL1Y7zZ-utaVIe19PBHX_mZTeidg92vJME/edit?usp=sharing)

**Comment by Adhel-Esteban1** [comment]
@PinkSylvie Thank you for sharing the test plan! I'll be sure to take a look at these for the presentation.

**Comment by Adhel-Esteban1** [comment]
Priority: 6
Difficulty: 3
