### ISSUE TITLE
Add Domain Requirements  to the documentation

### ISSUE THREAD

**Issue by Ryan8702** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#30]
• Domain requirements are derived from observations of the domain and the decision or the insight that a phenomenon or concept needs to be "simulated" or "operated" inside the machine. These phenomena and concepts will have certain properties in the domain and since we want the system-to-be to faithfully operate that part of the domain, these properties become requirements on the system-to-be. For example, if you observe in the domain that an artwork always has at least one artist as its creator and you decide that the concepts of artwork, artist, and creating will be simulated by your system-to-be, then you can derive a domain requirement like "the system must associate to every artwork the non-empty set of artists who are the creators of that piece".
  • Conversely, the requirement "The platform must be able to store the user's profile" is not a domain requirement if we assume that "user's profile" is not a domain concept. On the other hand, if you observe in the domain that comments are made by people and that the person making a comment can be identified (assuming this were so) and you decide that the concepts of comment, person, and identifying will be simulated by your system-to-be, then you can derive a domain requirement like "the system must provide a way to identify the person making a comment".
  • In the requirements "must allow" is not as good as "must provide means to": one can always claim that "must allow" is satisfied: "It doesn't forbid it, so this requirement is satisfied." You might want to say "must provide means to".

**Comment by PinkSylvie** [comment]
Hello! I see this part of the documentation is missing, would just like to remind you that tasks are due tomorrow so that we have Friday for review and so that we are able to turn the documentation in.

**Comment by PinkSylvie** [comment]
Could you change all the must be able to, to "must provide means to" so that it fits better with what the professor wants? @FrHend-Raul

**Comment by PinkSylvie** [comment]
Just checked, thanks for editing!
