### ISSUE TITLE
[Lecture Topic Task] Defect Report Template

### ISSUE THREAD

**Issue by misaelmercado1** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#304]
Make a Defect Report template so bugs can be easily organized and reproduced so testers can follow a plan with documentation.
difficulty = 4
urgency = 4

**Comment by PinkSylvie** [comment]
Hey, you have to create your own LTT tasks. Feedbacks were made, reason why I'm @ you here

**Comment by misaelmercado1** [comment]
Heres the link to the google drive that the template is in , i made the template in a word template format. https://drive.google.com/file/d/1pw4MXNiB3_77VPKh9TVtHk-dPS2lGZys/view?usp=drive_link

**Comment by PinkSylvie** [comment]
Please add this to the team's google drive and afterwards I'll close the task https://drive.google.com/drive/folders/1qbREwXYbhnB2045r_BsRdbvGRT3om4ys?usp=drive_link

**Comment by misaelmercado1** [comment]
ok perfect , adding it right now

**Comment by misaelmercado1** [comment]
just added to google drive

**Comment by PinkSylvie** [comment]
Just saw it, good work!
