### ISSUE TITLE
[Lecture Topic Task] Restore Tests for `Eat` Minigame to previous state

### ISSUE THREAD

**Issue by CaribbeanCool** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#305]
Restore eat tests to previous state and make sure that merges done after this one aren't lost. 

Points:
- Difficulty: 4
- Priority: 4

**Comment by CaribbeanCool** [comment]
@PinkSylvie @irsaris

**Comment by PinkSylvie** [comment]
Please add the tests ran into the documentation

**Comment by PinkSylvie** [comment]
@CaribbeanCool I reopened and changed the task description
