### ISSUE TITLE
[Lecture Topic Task] Defect Reporting for bugs

### ISSUE THREAD

**Issue by misaelmercado1** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#307]
Make a daily Defect Error Report daily to document all the bugs that were found on the given day.
urgency = 4
difficulty  = 4

**Comment by misaelmercado1** [comment]
No bugs found as of today for main branch

**Comment by misaelmercado1** [comment]
[Defect_Report#1_Pet_Creation.docx](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/files/15087409/Defect_Report.1_Pet_Creation.docx)

**Comment by PinkSylvie** [comment]
Please add the defect report information into the documentation in a suitable section. Afterwards the task will be closed

**Comment by misaelmercado1** [comment]
i still have found some bugs that need documentation , im gonna write atleast two more reports then add them to the documentation.

**Comment by misaelmercado1** [comment]
Defect Report Information added to the documentation in section 4.17

**Comment by PinkSylvie** [comment]
Just read it, good work!
