### ISSUE TITLE
[Lecture Topic Task] Black Box Testing and Run More Tests

### ISSUE THREAD

**Issue by JorgeC08** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#308]
Black Box testing to assess the software from an external perspective, focusing on functionality according to user requirements.

**Comment by PinkSylvie** [comment]
Please add further description on what you'll do an expected scoring asap, the milestone is due tomorrow

**Comment by PinkSylvie** [comment]
Just approved and scored it, make sure to add your tests information into the documentation

**Comment by JorgeC08** [comment]
Made this 3 test from the clients point of view:
Test 1: Flashcard Creation and Viewing Functionality
Passed: Users can create, view, and delete flashcards. All functionalities worked as expected, reflecting the necessary changes in the UI.
Test 2: Background Change Functionality in Settings
Passed: Background settings can be changed by the user, with the new settings persisting upon navigation. The functionality confirmed to work across 'Kitchen', 'Living Room', and 'Yard' options.
Test 3: Pet Name Display Consistency
Passed: The pet's name 'Firulai' was displayed consistently across the 'My Pets' overview page and the 'Player Stats' detail page without discrepancies.

All test cases concluded meeting the expected outcomes.

**Comment by PinkSylvie** [comment]
Did you add this to the documentation like the other tests?

**Comment by PinkSylvie** [comment]
Good work!
