### ISSUE TITLE
Add Interface Requirements to the documentation

### ISSUE THREAD

**Issue by Ryan8702** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#31]
• Interface requirements are about shared phenomena and concepts: phenomena and concepts that can be observed in the domain and that are relevant to the simulation of part of the domain in the system-to-be and how they are shared between the domain and the internal representation inside the system. For example, in a project revolving around cooking, recipes, ingredients, and learning different dishes how often I have prepared a given dish is a concept from the domain and let's assume you have decided that it is relevant to the requirements of your application and so must be represented inside the system-to-be. How is value in the system-to-be initialized? From which observation in the domain? How is it updated when a dish is actually prepared in the outside world? Is there a connection to the cook's kitchen, to their stove, or does the system-to-be provide a screen in which the cook clicks a "Prepared" button to increase the number?  These are all interface considerations and your choices are captured as interface requirements.
  • There are many more interface requirements: can information about outside phenomena and concepts that was incorrectly or incompletely entered be updated? Can such information be edited? Can it be changed? In which ways? Which information should not be changed once it was entered?
  • Many of your interface requirements can be derived by looking at the domain requirements, seeing that they require some concepts from the domain to be represented inside the system-to-be and then asking yourself: "how is that internal data representation first obtained? How is it kept up-to-date when the phenomenon in the domain changes?"

**Comment by PinkSylvie** [comment]
Hello! I see this part of the documentation is missing, would just like to remind you that tasks are due tomorrow so that we have Friday for review and so that we are able to turn the documentation in.

**Comment by AnthonyMed13** [comment]
@PinkSylvie I finished and added the interface requirements to the documentation

**Comment by AnthonyMed13** [comment]
Hi just wanted to see if you could check this to close the issue @irsaris @PinkSylvie

**Comment by PinkSylvie** [comment]
> Hi just wanted to see if you could check this to close the issue @irsaris @PinkSylvie 

Just checked!
