### ISSUE TITLE
Add Implementation to the documentation

### ISSUE THREAD

**Issue by Ryan8702** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#33]
Missing in Documentation Sections  

• Software architecture captures the big picture: what are to overall components and how are they related?
  • Software design captures more detail: what is used to realize each of the individual components?
  • When you use diagrams make sure that the diagrams _complement_ the textual explanation.
  • You can show screen designs here also. Again, if you do this then make sure that the screens are _complementing_ e.g. usage scenarios and how these are covered/supported by the screens you preview.

**Comment by irsaris** [comment]
There must be a graph for software architecture as well as software designs, i have sent you a dm with examples.

**Comment by PinkSylvie** [comment]
Please dont close tasks on your own without getting them reviewwd first by @irsaris  or me

**Comment by diego-velez-upr** [comment]
@PinkSylvie @irsaris can ya'll review this task?

**Comment by irsaris** [comment]
Thanks for adding what was missing, all looks good to me.

**Comment by PinkSylvie** [comment]
Quick detail regarding the software architecture. When referring to the parts it would be better to refer to them instead of by team, by the parts themselves. The team designs and implements the architecture but they aren't the software architecture.it reads more as a description of the teams instead of one of the architecture

**Comment by diego-velez-upr** [comment]
> Quick detail regarding the software architecture. When referring to the parts it would be better to refer to them instead of by team, by the parts themselves. The team designs and implements the architecture but they aren't the software architecture.it reads more as a description of the teams instead of one of the architecture

Fixed it

**Comment by irsaris** [comment]
@diego-velez-upr could you also add a snippet of code? thanks!

**Comment by diego-velez-upr** [comment]
> @diego-velez-upr could you also add a snippet of code? thanks!

Done

**Comment by irsaris** [comment]
Great, nice work!
