### ISSUE TITLE
[2.3.1] Add Selected Fragments of Implementation  to the documentation

### ISSUE THREAD

**Issue by Ryan8702** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#34]
• Selected fragments of the implementation are only used when they complement other presentations. Consider this: you are explaining some concepts and operations in natural language text and that explanation alone becomes awkward, but if you show some source code fragments (or diagrams, or …) along with the natural language explanation it becomes clear. That's where you use the fragments of implementation. When adding code fragments please utilize snippets of the actual code instead of writing it on word or using screen shots. By themselves diagrams and fragments of source code are not helpful. They are only useful if there is something that you want to explain/describe, the explanation is too complicated/awkward in natural language only, and the explanation becomes much easier to understand if one includes some pieces of the implementation. So, only when these implementation details complement your documentation should you include them. Never for their own sake.

**Comment by irsaris** [comment]
@joel-alvarado this section is in the criteria for this class also.
