### ISSUE TITLE
Add Concept Analysis  to the documentation

### ISSUE THREAD

**Issue by Ryan8702** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#35]
• When you want to do domain concept analysis you need to take the domain rough sketch (obtained from interviews, common knowledge, literature review, …) and analyze what the common concepts are.
  • So, base your concept analysis on some rough sketch where you use the rough sketch and hold parts of it side-by-side to justify some decision you are taking.
  • "User" is not normally a domain concept.
  • When analyzing the domain rough sketch remember to stay within the domain (no system-to-be). When analyzing requirements rough sketches (e.g. as user stories) you may find terms that belong to e.g. the application functions or the implementation and not to the domain.
  • Rough sketches are meant for collecting ideas in brainstorming, meeting recordings, Q&A, clippings from the literature, …

**Comment by PinkSylvie** [comment]
Please reach out to @AnthonyMed13 who is writting the rough sketch , the concept analysis is done based on concepts you gather up from the rough sketch. In the concept analysis you bring up those terms and say what from the rough ketch makes them concepts of the domain.

**Comment by Fabian-J** [comment]
Concept Analysis has been added and edited to reflect what should be part of the Domain Rough Sketch.

**Comment by PinkSylvie** [comment]
> Concept Analysis has been added and edited to reflect what should be part of the Domain Rough Sketch.

Can't approve it till it reflects not on what should be part of the domain rough sketch but on what is part of the domain rough sketch. We don't want the professor taking points off because a concept that was never mentioned in the rough sketch was brought up in the analysis. The rough sketch goes first, then the concept analysis, then the terminology. The rough sketch task is #26

**Comment by AnthonyMed13** [comment]
> > Concept Analysis has been added and edited to reflect what should be part of the Domain Rough Sketch.
> 
> Can't approve it till it reflects not on what should be part of the domain rough sketch but on what is part of the domain rough sketch. We don't want the professor taking points off because a concept that was never mentioned in the rough sketch was brought up in the analysis. The rough sketch goes first, then the concept analysis, then the terminology. The rough sketch task is #26

I sent him a copy of my rough sketch I am not in my apartment so I cannot send it to the documentation yet.

**Comment by PinkSylvie** [comment]
Thank you for clarifying. Once it is added I'll approve both tasks and close them, just @ me when you do 👍 @AnthonyMed13

**Comment by PinkSylvie** [comment]
Little detail regarding the concept analysis, it needs to reference and explain from where and why in the rough sketch it got that concept. Not just define the concepts. You analyze the rough sketch to get the concept and that analysis goes in the concept analysis. Then based on the analysis the terminology defines the concepts @Negroni1

**Comment by Fabian-J** [comment]
Some more context regarding which parts of the Domain Rough Sketch were referenced in the Concept Analysis. If there is anything specific i missed feel free to point it out

**Comment by PinkSylvie** [comment]
You defined further but you didn't quote or explain from where or what or who in the rough sketch you got those concepts. You didn't write an analysis for the concepts

**Comment by Fabian-J** [comment]
I have more directly referenced the Rough Sketch. I believe I have provided an analysis of each concept. If this is insufficient could some previous examples be provided? I have been using my own but evidently, they are inadequate.

**Comment by PinkSylvie** [comment]
> I have more directly referenced the Rough Sketch. I believe I have provided an analysis of each concept. If this is insufficient could some previous examples be provided? I have been using my own but evidently, they are inadequate.

To reference I mean to bring up how from X and Y quotes in the rough sketch you were able to see a similarity with their comments to come to the concept Z. In the rough sketch again you are describing the concepts not writing what you analyzed from the rough sketch to reach that conclusion and concept

**Comment by Fabian-J** [comment]
I have added direct quotes from the Rough Sketch to the remaining Concepts and removed Concepts that lacked evidence. I believe I have explained my analysis of each Concept.

**Comment by PinkSylvie** [comment]
To quote you are giving examples not quoting to analyze what you quoted

**Comment by PinkSylvie** [comment]
And there's plenty of rough sketch is that really the only two concepts you got out of them

**Comment by PinkSylvie** [comment]
Nice work!
