### ISSUE TITLE
Create Animations

### ISSUE THREAD

**Issue by Negroni1** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#43]
Design pets animations such as eating, cleaning, etc.

Priority: low
Difficulty: medium

**Comment by Negroni1** [comment]
Animations: @PinkSylvie Please review

![Image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/64982360/baa9689c-363a-4d41-9bde-b2f031f0f07b)
![Image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/64982360/75bb5559-fca5-48a7-9a63-dbeadb9993e8)
![Image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/64982360/0b0f3041-ef96-4b77-b6ed-a26b837d15a3)
![Image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/64982360/eb629a0f-3198-44e0-8d9e-5ffb715cc40d)
![Image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/64982360/be635df7-f490-4c9c-8b2f-588f0d8bc11f)

**Comment by PinkSylvie** [comment]
> Animations: @PinkSylvie Please review
> 
> ![Image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/64982360/baa9689c-363a-4d41-9bde-b2f031f0f07b)
> ![Image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/64982360/75bb5559-fca5-48a7-9a63-dbeadb9993e8)
> ![Image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/64982360/0b0f3041-ef96-4b77-b6ed-a26b837d15a3)
> ![Image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/64982360/eb629a0f-3198-44e0-8d9e-5ffb715cc40d)
> ![Image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/64982360/be635df7-f490-4c9c-8b2f-588f0d8bc11f)
> 
> 

They look so adorable! Could you make one more opening and closing its mouth?

**Comment by PinkSylvie** [comment]
Could you add all the animations and expressions and designs to its own folder on the team drive oso that other teams have easy access to the pet in the highest quality possible. And link the folder here. Other than that I think everything looks great! Great work!
