### ISSUE TITLE
[Lecture Topic Task] Document snapshot testing in milestone document

### ISSUE THREAD

**Issue by Axl4767** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#44]
Document snapshot testing implemented into the Pet Shop component as per #102

**Comment by irsaris** [comment]
Reminder: This task is due today before midnight.

**Comment by PinkSylvie** [comment]
Please include the results of the test in the documentation asap so I can close this task

**Comment by joel-alvarado** [comment]
Added (reference here for ease of access)

![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/77513199/863acfc2-70f4-49fa-87c6-db71b75529ee)

**Comment by PinkSylvie** [comment]
Saw it in the doc as well, great work!
