### ISSUE TITLE
Write Function Signatures

### ISSUE THREAD

**Issue by Axl4767** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#45]
For the function signatures think about what it takes to carry out the action, what information will be need and what will be produced/changed. For example, registering a member: Where is the new member registered? In the gym? In the gym's records? In a membership book? Depending on how you see this the signature would have to be changed. Examples registerNewMember : Gym >< Client -> Gym says that registering a client as a new member in a gym produces a (likely changed) gym, registerNewMember : MembershipBook >< Client -> MembershipBook reflects that the change is more local, it does not pull in as many dependencies since the concept membership book would be one that is accessible from gym, but other dependencies from gym would be left out. registerNewMember : MembershipBook >< Client -> MembershipBook >< Membership would report the newly created membership as part of the result of the operation. If the operation is one that can fail, you may want to provide for that possibility: registerNewMember : MembershipBook >< Client -> MembershipBook >< (Option Membership) where Option would be a datatype wrapping a possible result or providing an indicator for failure.
Exercising would be a good candidate for a behavior, where a client performs an exercise, then changes to a different station, … possibly rests in between, …

**Comment by PinkSylvie** [comment]
Hello! I see this part of the documentation is missing, would just like to remind you that tasks are due tomorrow so that we have Friday for review and so that we are able to turn the documentation in.

**Comment by Axl4767** [comment]
@irsaris @PinkSylvie I added the contents to the documentation
