### ISSUE TITLE
Design Home Page Screen

### ISSUE THREAD

**Issue by FrancesC8** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#46]
Design the Home Page hub following the sketches in issue #2. This can be designed either in Canva or Figma. When finished, make available the link for easy access to the design. Collaborating with the Homepage design. 

Suggestion of points = (4*4)= 16

**Comment by FrancesC8** [comment]
Finished designing the home page in  [Figma](https://www.figma.com/file/06srqyYzX4tgifBA9j1w3X/Study-Pet-Designs?type=design&node-id=0-1&mode=design&t=LCoOdMKpm4TBBc5y-0). @PinkSylvie . 


![HomePageDesign_Pet](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/99444066/61b92872-c46e-44e0-b36e-e0d43f65a20e)

**Comment by PinkSylvie** [comment]
> Finished designing the home page in  [Figma](https://www.figma.com/file/06srqyYzX4tgifBA9j1w3X/Study-Pet-Designs?type=design&node-id=0-1&mode=design&t=LCoOdMKpm4TBBc5y-0). @PinkSylvie . 
> 
> 
> 
> 
> 
> ![HomePageDesign_Pet](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/99444066/61b92872-c46e-44e0-b36e-e0d43f65a20e)
> 
> 
> 
> 

Love the colors, nice work!
