### ISSUE TITLE
Add Domain Description to documentation

### ISSUE THREAD

**Issue by joel-alvarado** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#49]
## Information pertinent to this documentation:

**Understanding Domain Functions:**

Functions represent actions, operations, or activities that can be performed on or with entities in a domain. For instance, consider the concept of making an appointment, which can involve actions like "making," "canceling," or "attending." To represent this in code, we might start with a basic function like:

```swift
makeAppointment(forWho: Patient, when: Period) -> Appointment
```

However, as we delve deeper into the domain, we realize the need to handle conflicting appointments. To address this, we consider passing a list of available periods:

```swift
makeAppointment(forWho: Patient, when: Period, free: [Period]) -> Appointment
```

To account for the possibility of failure, where an appointment cannot be allocated due to lack of available slots, we can use the `Option` type:

```swift
makeAppointment(forWho: Patient, when: Period, free: [Period]) -> Option<Appointment>
```

**First-Class Citizens:**

When conceptualizing domain functions, it's essential to treat them as first-class citizens, detached from any specific entity. This ensures a more generalized and versatile approach.

**Structural Considerations:**

Care must be taken to ensure that the structures defined are suitable in general. For example, when describing a game as a domain entity, we must question whether every game necessarily involves rounds.

**Thorough Analysis of Domain Operations:**

Thoroughly analyze domain operations. For instance, when "adding an event," consider the elements involved: the event itself, the container (schedule), and the expected result (modified schedule).

**Purity of Domain Functions, Events, and Behaviors:**

Ensure that functions, events, and behaviors stem purely from the domain, devoid of any system-specific influence. The goal is to describe the domain independently of any system-to-be.

**Distinction Between Domain Description and Requirements:**

Differentiate between the domain description, which focuses solely on phenomena and concepts independent of any system, and the requirements, which outline what a system must do. User stories can capture requirements, utilizing domain concepts while incorporating system-specific elements like "session."

**Caution in System References:**

Exercise caution when referring to a system in domain descriptions. Reserve discussions about the system for requirement specifications.

**Project Foundations:**

Domain descriptions, terminologies, narratives, and related activities are essential for a well-founded project. They provide a solid basis for understanding the domain independently of the system-to-be.

---

Suggest for this task to have highest priority and urgency, since it is a task related to project documentation.

**Comment by irsaris** [comment]
This isn't a section, it's used as a header.

**Comment by PinkSylvie** [comment]
Hello! I see this part of the documentation is missing, would just like to remind you that tasks are due tomorrow so that we have Friday for review and so that we are able to turn the documentation in.
