### ISSUE TITLE
Set up code base for the React framework

### ISSUE THREAD

**Issue by Adhel-Esteban1** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#5]
In this task, your primary objective is to establish the foundational structure of the StudyPet project using the React framework. Create a basic skeleton that lays the groundwork for future development. Set up essential files and directories, including the **main application file**, **components**, **styles**, **and any necessary configuration files.** **Ensure that the project can be successfully initiated**, even if it displays a basic white screen on the phone. This initial setup provides a solid foundation for other developers to build upon, streamlining the collaborative development process and allowing for seamless integration of features and functionalities as the project progresses.

**Comment by PinkSylvie** [comment]
Late but great work!
