### ISSUE TITLE
Write Domain Terminology in relation to Domain Rough Sketch

### ISSUE THREAD

**Issue by joel-alvarado** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#50]
**Role of Domain Terminology:**

The domain terminology is a distinct entity from the rough sketch. Instead of being an inherent part of the initial sketch, it evolves through a dedicated analysis process. The terminology development involves a detailed examination of the rough sketch, often aided by stakeholder interviews.

**Terminology Development Process:**

To construct the domain terminology, one must meticulously scrutinize the rough sketch. This entails identifying key terms used in the sketch and proceeding to create precise definitions for each term. Stakeholder interviews can contribute significantly to gaining a comprehensive understanding of the concepts embedded in the rough sketch.

**Results of Processing:**

The definitions derived during the terminology development process are outcomes of systematic analysis. Unlike the rough sketch, these definitions are not considered rough; instead, they represent the refined and clarified meanings of the terms identified in the initial sketch.

**Clarity through Definitions:**

The aim of developing terminology is to bring clarity to the language used within the domain. By providing well-crafted definitions for each term, the domain terminology becomes a valuable resource for communication and understanding among project stakeholders.

**Evolution of Understanding:**

As the terminology evolves, it contributes to a deeper and more nuanced understanding of the domain. This understanding becomes a crucial foundation for further project activities, ensuring a shared language and meaning among all involved parties.

---

Scoring for this task is subjective, as from my understanding this part is to ensure that the relationship between the rough sketch and the terminology is kept.

**Comment by PinkSylvie** [comment]
Hello! I see this part of the documentation is missing, would just like to remind you that tasks are due tomorrow so that we have Friday for review and so that we are able to turn the documentation in.

**Comment by JonathanDebug** [comment]
@irsaris @PinkSylvie  the section has been added to the doc for review.

**Comment by PinkSylvie** [comment]
These all seem like more terminology terms. Nothing explains here what is the relation of the domain terminology with the rough sketch or the relation of the terms in the terminology to the rough sketch. But the task description wasn't really helpful since it talked more about the writing the terminology instead of writing this section.

**Comment by JonathanDebug** [comment]
From the description in the document it says he following: " The domain terminology is not part of the rough sketch: to develop the terminology you have to analyze the rough sketch and come up with good definitions for the terms used e.g. in stakeholder interviews. So, the definitions are results of the processing and are therefore not rough. ". What I took from this is that is the same as domain terminology but basing it on the rough sketch.

**Comment by PinkSylvie** [comment]
But the domain terminology is based on the rough sketch

**Comment by JonathanDebug** [comment]
I see, but Im not very sure of what it means in relation, ill try to find what i have to do and fix it.

**Comment by PinkSylvie** [comment]
I think it means how and why are the domain terms in the terminology related to the rough sketch

**Comment by PinkSylvie** [comment]
You are giving examples you are not analyzing their comments

**Comment by JonathanDebug** [comment]
I added what I could relate from the terminology to the rough sketch, see if it suffices. @irsaris @PinkSylvie

**Comment by PinkSylvie** [comment]
Just checked, nice work!
