### ISSUE TITLE
Establashing the Pet class

### ISSUE THREAD

**Issue by PurpleDerg** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#54]
In this task, the goal is to create the Pet class within the React Native framework. This will allow us to implement object oriented programming within the project giving us more freedom to implement new features moving forward. 
 The class should have the properties that a Pet object will have a few properties as an example, these are not final and some could be put in other classes. 

- Img
- name
- growth
- hunger
- Happiness 
- Deck (flashcard)

recommended task DIf*prio   Can differ upon managers review

-intermediate difficulty (4)
- high prio (6)

**Comment by irsaris** [comment]
Reminder: This task is due today before midnight.
