### ISSUE TITLE
set up User class

### ISSUE THREAD

**Issue by PurpleDerg** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#56]
The goal for this task is to make the User class that will hold the following properties as a base

-Pets ( A list of pets under the user's name)
-Exams (A list of exams under the User's name)
-Name -> self explanatory

DIfficulty and priority (recommended)
DIf: 4 ( intermediate)
Prio: 4 (medium)

**Comment by gabrielpadilla7** [comment]
assigned to work together on this task

**Comment by PurpleDerg** [comment]
working on setting up a User class

**Comment by irsaris** [comment]
Reminder: This task is due today before midnight.
