### ISSUE TITLE
Set up the Page interface

### ISSUE THREAD

**Issue by PurpleDerg** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#57]
The goal of this task is to set up and interface that will hold the properties of what a "page" would be in the app. 
Like the home page, the pets stats page, and the settings page, to give an example. 

The interface should have these properties that other pages will be inheriting from 

- Title
- Header
- Content 

Recommended DIfficulty and priority 
Diff: Intermediate (4)
Prio: High (6)

**Comment by misaelmercado1** [comment]
Working with Sebastian Granda on this task

**Comment by irsaris** [comment]
Reminder: This task is due today before midnight.

**Comment by PinkSylvie** [comment]
There was an explosion due to a merge so we are closing these tasks since they are pretty much done just not merged into main yet
