### ISSUE TITLE
Implementing a UML diagram of the class hiererchy

### ISSUE THREAD

**Issue by PurpleDerg** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#58]
The goal of this task is to have a UML diagram for the purpose of documentation. 
The UML diagram would be detailing, the which class inherits from which as well as detailing it's various properties and methods in an easy to read diagram. 

To give an example: 
Page interface -> home page -> settings page... etc. 

Recommended Difficulty and Prio:
diff: Easy( 2)
prio: medium (4)

**Comment by gabrielpadilla7** [comment]
Assigned to work together on this task

**Comment by gabrielpadilla7** [comment]
![Image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/112046903/d5d3cb7f-b6c4-4cd0-9867-949ccf472f11)

Here is the UML diagram, if there's any issues with it, please let me know and I will modify

**Comment by gabrielpadilla7** [comment]
@PinkSylvie

**Comment by gabrielpadilla7** [comment]
Added to the documentation, in section 2.3.3

**Comment by PinkSylvie** [comment]
> Added to the documentation, in section 2.3.3

Just checked, nice work!
