### ISSUE TITLE
Create a small demo for the milestone presentation

### ISSUE THREAD

**Issue by gabrielpadilla7** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#65]
Create a small demo to show off the features implemented (as well as the tests) done to the application for the first milestone. The demo needs to include everything that has been worked on.

Suggested scores:
Difficulty: (2)
Priority: (2)

**Comment by irsaris** [comment]
@gabrielpadilla7 this is the video that will be in the presentation right? It'll be done before Monday class?

**Comment by gabrielpadilla7** [comment]
> @gabrielpadilla7 this is the video that will be in the presentation right? It'll be done before Monday class?

Yes! It'll showcase everything that was implemented for the first milestone. I'm just waiting until the program is fully finished so that I can play around with it and record the video.

**Comment by irsaris** [comment]
Okay great, for closed points sake I'll mark it as done.
