### ISSUE TITLE
"Record Voiceovers for the Presentation Video

### ISSUE THREAD

**Issue by Adhel-Esteban1** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#7]
Produce a professional and engaging voiceover to accompany the PowerPoint presentations for the milestone. Follow these guidelines to ensure a compelling presentation:

1. **Script Preparation:**
   - Develop a clear and concise script that aligns with the content of the PowerPoint slides.
   - Ensure the script covers key points, explanations of visual elements, and any additional insights that enhance understanding.
   - Aim for a conversational tone to maintain audience engagement.

2. **Voiceover Recording:**
   - Utilize high-quality recording equipment and a quiet environment to achieve clear audio.
   - Record the voiceover in a natural and confident manner, emphasizing key concepts and transitions.
   - Pay attention to pacing, allowing listeners to absorb information without feeling rushed or overwhelmed.

3. **Synchronization with Slides:**
   - Coordinate the voiceover timing with the PowerPoint slides for seamless integration.
   - Ensure that the narration complements the visual elements, providing a cohesive and immersive experience.
   - Always make sure to leave at least 3 seconds of silence before and after each slide. This will simplify the process for the editor.
   -  Say "next slide" every time you change a slide so the editor can time what you are saying.

4. **Share the audio/video with editor**
   -  This can be done with Google Drive for simplicity.

**Comment by irsaris** [comment]
Will close now for the sake of the closed points.
