### ISSUE TITLE
Design Stats Screen

### ISSUE THREAD

**Issue by benjaminCMD** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#75]
- Using the sketches created by the managers, design a strat screen for the pet in Canvas or Figma
- The stat attributes include happiness, hunger, and health 
- Alongside the page should indicate the care difficulty, exam date, also its name and picture profile

- Difficulty: Easy
- Priority: Low or Medium

**Comment by PinkSylvie** [comment]
Hello! I added your design to the group figma here: https://www.figma.com/file/06srqyYzX4tgifBA9j1w3X/Study-Pet-Designs?type=design&node-id=0-1&mode=design&t=BdShnbC7oI0eyBSI-0 Could you change the font of it to the of the loading screen Jua? And please finish adding the icons to it as well, and a space where the user can see their pet. When you finish please @ me here

**Comment by benjaminCMD** [comment]
@PinkSylvie I just finished making a draft of stats screen. I changed the font to Jua like you asked me too. I was also able to add hearts next to happiness stat, and cookies next to hunger stat. Additionally, I added the pet icon into the screen. If there is any changes that needs to be made, you can @ me here as well

**Comment by PinkSylvie** [comment]
Looks great! Nice work!
