### ISSUE TITLE
[Lecture Topic Task] Add Validation and Verification Processes into the documentation

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#77]
Add to the documentation the project's Validation and Verification processes. Anything that has to do with stating a property about you deliverables that then needs to be checked goes here. Does your project employ testing? Yes: describe what kinds of testing will be
  used, how, when, who, why you do this kind of testing. Have you done
  any walkthroughs of your requirements using scenarios? Who did those?
  Did you find any gaps in the requirements? What remedies did you come
  up with?

**Comment by PinkSylvie** [comment]
Hello! I see this part of the documentation is missing, would just like to remind you that tasks are due tomorrow so that we have Friday for review and so that we are able to turn the documentation in.

**Comment by misaelmercado1** [comment]
Yeah im working on it in a doc , when i finish it i will add it to the main document

**Comment by PinkSylvie** [comment]
About some of the tests I see you are speaking of tests that are going to be done but you haven't spoken about those that were done. Could you also spell check your section please?

**Comment by PinkSylvie** [comment]
Also you are writing about tests that haven't and with our timing won't be done. Maybe speak of them as a next milestone thing but unlikely that in this one

**Comment by misaelmercado1** [comment]
on it

**Comment by misaelmercado1** [comment]
can i have something that has all of the testing methods used in this milestone ? i cant seem to find them

**Comment by PinkSylvie** [comment]
The testing tasks in the board and at the end of the documentation

**Comment by misaelmercado1** [comment]
Can u verify it again , i spell checked , emphasized on the first paragraph , what was used for this milestone  and what will be for the next milestone , and on the second paragraph emphasized on what was done for this particular milestone

**Comment by PinkSylvie** [comment]
Just checked, nice work!
