### ISSUE TITLE
Implement one Base Flashcard Minigame triggered when an action is done

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#78]
Follow up with the designs and ideas of issue #12 to develop one of them for this milestone. 

Es an example: the app can randomize up to ten flashcards on the set and for each randomize three answers and the correct one and make a simple quiz with the up to ten flashcards. The minigame can do the desire effect if you finish it, but if you do excellent (all correct) it can give a boost on the desired pet stat.

Tentative score : Difficulty hard (6 pts) x Priority medium (4 pts)

**Comment by irsaris** [comment]
Reminder: This task is due today before midnight.

**Comment by PinkSylvie** [comment]
Pleaseadd the video of your implementation here as well for documentation sake so I can close the task

**Comment by FrHend-Raul** [comment]
https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/60901470/37ecdead-2709-42c8-909c-b68fe6221575

**Comment by irsaris** [comment]
can you link a pull request to this? even if its on a separate branch
