### ISSUE TITLE
Connect Pet with Flashcards so that after a minigame is played the Pets Stats Change

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#79]
Follow up with Issue #78 so that after a minigame is won, pet's stats are increased. Hunger after doing a hunger game (riggered after pressing the hunger button), happiness after doing a cleaning or just playing a game game.

Hunger has 8 tabs 
Feeding mini game at max can give 2 tabs if played perfectly
1 tab if score is less than 100 and more than 50
0 tab if score less than 50

Happiness has a tab that goes from 0 - 100
Playing Raises Happiness by 10 if done perfectly, by 5 otherwise

**Comment by irsaris** [comment]
Reminder: This task is due today before midnight.

**Comment by irsaris** [comment]
This task is being moved to the next milestone.

**Comment by irsaris** [comment]
link the pull request here

**Comment by misaelmercado1** [comment]
https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/pull/222
https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/pull/217

**Comment by misaelmercado1** [comment]
waiting for pull request , task is done
