### ISSUE TITLE
Implement Stats Screen 

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#80]
Following up on issues #75 and #79

Implement the Stats Screen into the Project so that it follows the design and so that it reflects the pets attributes including:

- The pet's name
- The exam date 
- Its happiness 
- Its hunger 
- The Study Difficulty 

The pet will be connected to it at a later milestone

**Comment by irsaris** [comment]
Reminder: This task is due today before midnight.

**Comment by PinkSylvie** [comment]
@JConcepcion01 Dis you finish this? And if you did screenshot, link this task to the pull request ASAP so I can close this

**Comment by JConcepcion01** [comment]
![Image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/99218117/831e66eb-25d4-4780-8c4a-db703f819cb3)

**Comment by PinkSylvie** [comment]
There was an explosion due to a merge so we are closing these tasks since they are pretty much done
