### ISSUE TITLE
[Lecture Topic Task] Add Examples TDD testing into the Documentation

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#81]
Follow developers doing implementation issues and add to the documentation examples of using the TDD tetsing method into the documentation. The examples
    present an initial, formal or informal specification of a unit
    (e.g. function). They then present a first, minimal test capturing
    some aspect of the specification together with a dummy
    implementation (a stub) that fails the test, to then modify the
    implementation so it passes the test. This is repeated for at least
    a total of 5 tests (thereby building up a test suite) each time
    changing the implementation so it then passes the new test in
    addition to the existing tests.

_Test-driven development (TDD) is a software development practice that emphasizes writing tests before writing the actual code. It follows a cyclical process of writing a failing test, writing the minimum code to make the test pass, and then refactoring the code._

More on TDD: https://www.browserstack.com/guide/what-is-test-driven-development#:~:text=Test%2Ddriven%20development%20(TDD)%20is%20a%20software%20development%20practice,and%20then%20refactoring%20the%20code.

**Comment by PinkSylvie** [comment]
Hello! I see this part of the documentation is missing, would just like to remind you that tasks are due tomorrow so that we have Friday for review and so that we are able to turn the documentation in.

**Comment by DiegoLIRodriguez** [comment]
TDD cases have been carried out and added to documentation. Link here: https://docs.google.com/document/d/1nkb1ZZu2VTyXXfE5-2ENqSvHr6rieFGHmW2IOq3gIKM/edit#heading=h.nxw6a2t2ve43

**Comment by PinkSylvie** [comment]
> TDD cases have been carried out and added to documentation. Link here: https://docs.google.com/document/d/1nkb1ZZu2VTyXXfE5-2ENqSvHr6rieFGHmW2IOq3gIKM/edit#heading=h.nxw6a2t2ve43

Just checked. Nice work!
