### ISSUE TITLE
Design Pet Creation Screen

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#82]
Following the UI Sketches in issue #2 design the Pet Creation Screen using Figma or Canvas

**Comment by Fabian-J** [comment]
The font has been changed. Sorry for closing without asking.

**Comment by PinkSylvie** [comment]
No worries, can you send a screenshot over here of what you did to document the completion of the task and link the figma in the comment and that should be enough to close the task. Thank you for responding so swiftly

**Comment by Fabian-J** [comment]
![Screenshot_20240221_161334_Chrome](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/78558274/4ed5fe43-2f00-4161-a936-1e93c204c337)
This is what was created. Here is the link:
https://www.figma.com/file/vwYsj9czX0Blp7zyzjhIuq/Pet-creation-screen?type=design&node-id=0%3A1&mode=dev&t=ndLqer4OIDrbYPTk-1

**Comment by PinkSylvie** [comment]
Looks nice, the shadows do make everything stand out!
