### ISSUE TITLE
Implement Pet Creation

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#84]
Following up on issue #82, Implement the screen where a new pet is created, a user gives the pet a name, chooses their exam date, and picks a study/care difficulty. A pet will also start with a full happiness stat and hunger stat. All of these will be attributes of the created pet. A pet will also start with a full happiness stat and hunger stat. After these screen it will take you to the flashcard creation screen in issue #38

**Comment by irsaris** [comment]
Reminder: This task is due today before midnight.

**Comment by Mark-Anton** [comment]
You can name the new pet. 
Add date within a preset format, if the user inputs the date incorrect the app will give an error and allow the user to fix the format before creating the pet.
The user is able to adjust difficulty by clicking on the "Select Difficulty:"button and menu will pop on the top part of the screen to allow the user to select easy, medium and hard and it will update to reflect the difficulty.

![Screenshot_20240223_215602_Expo_Go](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/42784582/05a9c308-f6c7-4aa4-8c71-80b71226a68e)

![Screenshot_20240223_215631_Expo_Go](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/42784582/baa88ebb-ee4f-4eff-9873-d4dacd1bd3bb)

![Screenshot_20240223_215637_Expo_Go](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/42784582/fd7fcbab-7605-478d-a373-b24b823faa2b)

![Screenshot_20240223_215642_Expo_Go](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/42784582/b7d50f14-5630-4ce7-b1ca-0e0f1859c4cd)

![Screenshot_20240223_215657_Expo_Go](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/42784582/b70dd2b9-64b4-4eca-bbcb-5e6e19354061)

**Comment by irsaris** [comment]
can you link a pull request to this?

**Comment by PinkSylvie** [comment]
There was an explosion due to a merge so we are closing these tasks since they are pretty much done just not merged into main yet
