### ISSUE TITLE
Add images and animations to the Pet Component

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#85]
Follow up with issues #41, #42, #43, to add the images and animations they created into the pet component and allow them to appear into the application.

**Comment by PinkSylvie** [comment]
There was an explosion due to a merge so we are closing these tasks since they are pretty much done just not merged into main yet

**Comment by Mark-Anton** [comment]
The pet animation was implemented on the homescreen and changes from a set of gifs in 3 second intervals on repeat.

https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/42784582/3b73ab3d-7ae8-4c7e-bf70-01485498a4fc
