### ISSUE TITLE
Implement Poop

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#86]
Implement so that a poop appears if there's no poop on the screen already every 2 hours. If a poop is left without cleaning for an hour it'll decrease the pet's happiness by 10 every hour is left unattended. To remove the poop from the screen the player will have to clean the pet, so play a cleaning minigame, the care minigame is another issue on the board. Poop just needs something to tell it when to appear, when to dissapear and to lower the pet's happiness every hour is left uncleaned.

Difficulty: 4
Priority: 5

**Comment by irsaris** [comment]
Hello, where is the PR for this?

**Comment by Mark-Anton** [comment]
Poop implementation [#225](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/pull/225)

Poop icon and counter:
![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/42784582/32416bb0-f357-4047-80cf-c7cb487f36a7)
