### ISSUE TITLE
Implement Hunger and Happiness Decrease

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#87]
Implement so that the pet's happiness stat decreases by 10 every hour that passes by and so that the hunger tab decreases by 1 tab every hour that passes by.

A pet's hunger tab goes from 0-8 tabs
A pet's happiness tab goes from 0-100 happiness points

Make sure this change is reflected in the pet's stats screen and its hunger and happiness bars

**Comment by irsaris** [comment]
Reminder: This task is due today before midnight.

**Comment by irsaris** [comment]
@JConcepcion01 can you make the pull request for this?

**Comment by irsaris** [comment]
@JConcepcion01 will you be doing this task for this milestone? If not there's someone else willing to do so.

**Comment by JConcepcion01** [comment]
I created the pull request for this

**Comment by irsaris** [comment]
link the pull request

**Comment by JConcepcion01** [comment]
Not sure if i did it correctly ^^' Lemme know

**Comment by irsaris** [comment]
Yes, it was done correctly.
