### ISSUE TITLE
Design the remove flashcard and study set component

### ISSUE THREAD

**Issue by FrHend-Raul** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#89]
These two components should delete the desired unique flashcard or the study set, the user should be notified to be sure before deleting these. User can choose when deleting a study set to also delete all flashcards that are from that study set.

Tentative score: Medium priority (4 pts) x hard difficulty (6 pts)

**Comment by irsaris** [comment]
@PinkSylvie thoughts on this task?

**Comment by PinkSylvie** [comment]
Isn't it done already?
