### ISSUE TITLE
Create a base set of flashcards

### ISSUE THREAD

**Issue by FrHend-Raul** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#91]
Create and implement on the code a dummy set of flashcards on basic general material up to 10 cards to enable testing of flashcard features

Tentative score: Medium priority (4 pts) x Easy difficulty (2 pts)

**Comment by irsaris** [comment]
Reminder: This task is due today before midnight.

**Comment by PinkSylvie** [comment]
There was an explosion due to a merge so we are closing these tasks since they are pretty much done just not merged into main yet
