### ISSUE TITLE
Implement "My Pets" Screen

### ISSUE THREAD

**Issue by PurpleDerg** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#93]
Implementing the "my Pets" Screen class.
This task would be consider done once the "my Pets" screen can hold the following properties and methods as a base to work on:

Properties:
-List of Pet Objects (that will have the PET type classification)

Methods
-CreatePet() -> Let's you create a new PET object

*as for the buttons, let's leave that for a NAV BAR. 

Recommend Difficulty and Priority
Diff: 2
Prio: 6

**Comment by irsaris** [comment]
Reminder: This task is due today before midnight.

**Comment by irsaris** [comment]
This task was not completed in time. This task is being moved to the next milestone.

**Comment by PurpleDerg** [comment]
Creating a new pet, would be link to the Async storage and would be saved locally in the device.

**Comment by irsaris** [comment]
Hello, where is the PR for this?

**Comment by Mark-Anton** [comment]
My Pets Selection Screen [#224](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/pull/224)

Inicial pet screen:
![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/42784582/4e6e62c6-5f6a-4854-943e-531ef76abc2b)

Two empty slots:

![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/42784582/49df82f6-6ff8-47b8-a4a1-431fffd93351)
![image](https://github.com/uprm-inso4117-2023-2024-s2/semester-project-study-pet/assets/42784582/5684777c-f67b-4a01-be51-8d852dfc9b65)
