### ISSUE TITLE
Design/Implement Overview of Flashcards

### ISSUE THREAD

**Issue by CaribbeanCool** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#95]
The idea is to implement and design in Figma a page displaying all the users' created flashcards. Follow the UI sketch for an idea of the design

Points: TBD

**Comment by CaribbeanCool** [comment]
@PinkSylvie @irsaris Ya puse mi design del overview de los flashcards en Figma.

[Link to Figma](https://www.figma.com/files/project/203954874/Team-project?fuid=1281418873391416493)

**Comment by PinkSylvie** [comment]
@CaribbeanCool Could you pass the design to the Study Pet Designs Figma file? We want everyone's designs in one place. Also could you use a rounder font? It looks like too rigid of a font

**Comment by CaribbeanCool** [comment]
> [@CaribbeanCool](https://github.com/CaribbeanCool) Could you pass the design to the Study Pet Designs Figma file? We want everyone's designs in one place. Also could you use a rounder font? It looks like too rigid of a font

@PinkSylvie Ya lo puse en el file indicado.

**Comment by CaribbeanCool** [comment]
@PinkSylvie I published my branch for the overview of the flashcards with very basic functionality
