### ISSUE TITLE
Study Reminder Notifications

### ISSUE THREAD

**Issue by JonathanDebug** [uprm-inso4117-2023-2024-s2/semester-project-study-pet#98]
Implement a feature where the pet reminds users at certain intervals to take study breaks or start their study sessions. Could be notifications like [Pet Name] misses you, you haven't studied in abit and etc.

**Comment by irsaris** [comment]
Sorry, didn't notice this one was created first

**Comment by JonathanDebug** [comment]
Task has been done, check PR to close this issue.
